import type {
  MelanieSemanticFingerprint,
} from "./melaniesGame";

export type ExpandedMelanieSemanticSeed = [
  premiseFamily: MelanieSemanticFingerprint["premiseFamily"],
  centralActivities: MelanieSemanticFingerprint["centralActivities"],
  settingClasses: MelanieSemanticFingerprint["settingClasses"],
  protagonistRoles: MelanieSemanticFingerprint["protagonistRoles"],
  narrativeEngine: MelanieSemanticFingerprint["narrativeEngine"],
  relationshipShapes: MelanieSemanticFingerprint["relationshipShapes"],
  speculativeDevices: MelanieSemanticFingerprint["speculativeDevices"],
  stakesShapes: MelanieSemanticFingerprint["stakesShapes"],
  keyCoverMotifs: MelanieSemanticFingerprint["keyCoverMotifs"],
  socialFocus: MelanieSemanticFingerprint["socialFocus"],
];
const kids: Record<string, ExpandedMelanieSemanticSeed> = {
  "k-umbrella-forecast": ["quest", ["discover", "protect"], ["home", "small-town"], ["student"], "cause-and-effect-discovery", ["family"], ["magic-object"], ["personal-belonging"], ["storm", "home"], "individual"],
  "k-worm-tunnel": ["quest", ["explore", "discover"], ["home", "other-world"], ["sibling"], "journey-encounters", ["siblings"], ["alternate-world"], ["personal-belonging"], ["journey", "forest", "magic"], "pair"],
  "k-recess-olympics": ["competition", ["compete", "organize"], ["school", "sports"], ["student", "organizer"], "rivalry-ladder", ["team"], ["none"], ["competition"], ["sport", "school"], "team"],
  "k-attic-orchestra": ["quest", ["discover", "perform"], ["home"], ["student"], "memory-reconstruction", ["family"], ["magic-object"], ["personal-belonging"], ["music", "home"], "family"],
  "k-pirate-homework": ["quest", ["create", "organize"], ["home"], ["student"], "deadline-mission", ["friendship"], ["impossible-creature"], ["personal-belonging"], ["sea", "book"], "pair"],
  "k-greenhouse-club": ["community-change", ["care", "negotiate"], ["garden"], ["organizer"], "community-project", ["community"], ["living-nature"], ["community"], ["garden", "food"], "community"],
  "k-lighthouse-keeper-jr": ["stewardship", ["protect", "lead"], ["coast"], ["apprentice"], "deadline-mission", ["mentor-student"], ["none"], ["public-duty"], ["coast", "storm"], "individual"],
  "k-time-capsule": ["investigation", ["discover", "organize"], ["school"], ["student"], "clue-chain", ["team"], ["none"], ["truth", "community"], ["history", "school"], "team"],
  "k-cloud-shepherd": ["stewardship", ["care", "protect"], ["wilderness"], ["caretaker"], "resource-management", ["solo"], ["living-nature"], ["livelihood"], ["storm", "garden"], "individual"],
  "k-invisible-friend": ["identity-discovery", ["discover", "reconcile"], ["home", "small-town"], ["outsider"], "secret-uncovering", ["friendship"], ["impossible-creature"], ["personal-belonging"], ["animal", "home"], "pair"],
  "k-marching-band-mixup": ["coming-of-age", ["perform", "lead"], ["school", "performance"], ["performer"], "escalating-trials", ["team"], ["none"], ["personal-belonging"], ["music", "city"], "team"],
  "k-snowglobe-town": ["rescue", ["restore", "care"], ["other-world"], ["caretaker"], "deadline-mission", ["solo"], ["alternate-world"], ["rescue"], ["storm", "magic"], "individual"],
  "k-farmyard-detective": ["investigation", ["investigate", "solve"], ["garden"], ["investigator"], "clue-chain", ["community"], ["communicating-animal"], ["justice"], ["animal", "food", "mystery"], "community"],
  "k-bike-race-map": ["quest", ["explore", "travel"], ["small-town"], ["traveler"], "journey-encounters", ["friendship"], ["magic-object"], ["personal-belonging"], ["journey", "machine"], "individual"],
  "k-museum-nightwatch": ["quest", ["discover", "protect"], ["institution"], ["caretaker"], "escalating-trials", ["family"], ["living-nature"], ["personal-belonging"], ["history", "animal", "science"], "family"],
  "k-quiet-superhero": ["identity-discovery", ["reconcile", "lead"], ["small-town"], ["outsider"], "moral-choice", ["solo"], ["transformation"], ["identity"], ["city", "magic"], "individual"],
  "k-recipe-heirloom": ["inheritance", ["cook", "discover"], ["home"], ["caretaker"], "cause-and-effect-discovery", ["family"], ["magic-object"], ["family"], ["food", "home"], "family"],
  "k-storm-chaser-jr": ["community-change", ["build", "organize"], ["small-town"], ["student", "scientist"], "deadline-mission", ["friendship"], ["none"], ["community"], ["storm", "signal", "machine"], "team"],
  "k-puppet-uprising": ["creation", ["create", "negotiate"], ["school", "performance"], ["artist"], "creative-process", ["team"], ["transformation"], ["creative-goal"], ["art", "performance"], "team"],
  "k-desert-caravan": ["journey", ["travel", "teach"], ["wilderness"], ["traveler"], "journey-encounters", ["friendship"], ["communicating-animal"], ["personal-belonging"], ["desert", "animal", "journey"], "individual"],
  "k-glowing-jar-fireflies": ["ethical-dilemma", ["care", "reconcile"], ["wilderness"], ["caretaker"], "moral-choice", ["family"], ["living-nature"], ["ethical"], ["forest", "magic"], "individual"],
  "k-robot-babysitter": ["relationship-repair", ["teach", "care"], ["home"], ["sibling"], "training-progression", ["found-family"], ["artificial-intelligence"], ["relationship"], ["machine", "home"], "family"],
  "k-treasure-map-classroom": ["quest", ["solve", "discover"], ["school"], ["student"], "clue-chain", ["friendship"], ["none"], ["personal-belonging"], ["school", "book"], "pair"],
  "k-lost-mitten-express": ["rescue", ["travel", "care"], ["wilderness"], ["worker"], "journey-encounters", ["solo"], ["communicating-animal"], ["rescue"], ["animal", "storm"], "individual"],
  "k-underdog-choir": ["coming-of-age", ["perform", "reconcile"], ["school", "performance"], ["student"], "training-progression", ["team"], ["none"], ["personal-belonging"], ["music", "school"], "team"],
  "k-comet-wish": ["quest", ["discover", "adapt"], ["home"], ["student"], "cause-and-effect-discovery", ["family"], ["mythic-being"], ["personal-belonging"], ["moon", "magic"], "individual"],
  "k-tidepool-rescue": ["rescue", ["rescue", "organize"], ["coast"], ["organizer"], "deadline-mission", ["team"], ["none"], ["rescue", "environment"], ["sea", "animal"], "team"],
  "k-quilt-of-stories": ["inheritance", ["discover", "care"], ["home"], ["caretaker"], "memory-reconstruction", ["intergenerational"], ["magic-object"], ["family", "legacy"], ["home", "art"], "family"],
  "k-substitute-wizard": ["identity-discovery", ["discover", "teach"], ["school"], ["student"], "secret-uncovering", ["team"], ["magic-object"], ["personal-belonging"], ["magic", "school"], "team"],
  "k-runaway-kite": ["journey", ["explore", "travel"], ["small-town"], ["student"], "journey-encounters", ["solo"], ["none"], ["personal-belonging"], ["journey", "city"], "individual"],
  "k-shoebox-spaceship": ["investigation", ["create", "solve"], ["home"], ["sibling"], "cause-and-effect-discovery", ["siblings"], ["magic-object"], ["community"], ["space", "machine", "home"], "pair"],
  "k-baker-apprentice": ["workplace-crisis", ["cook", "adapt"], ["workplace"], ["apprentice"], "deadline-mission", ["mentor-student"], ["none"], ["livelihood"], ["food", "city"], "individual"],
  "k-fossil-finder": ["investigation", ["discover", "negotiate"], ["home"], ["sibling"], "cause-and-effect-discovery", ["siblings"], ["none"], ["personal-belonging"], ["science", "history"], "pair"],
  "k-puddle-portal": ["quest", ["explore", "discover"], ["school", "other-world"], ["student"], "journey-encounters", ["solo"], ["alternate-world"], ["personal-belonging"], ["magic", "journey"], "individual"],
  "k-grumpy-old-tree": ["stewardship", ["reconcile", "protect"], ["garden"], ["student"], "community-project", ["community"], ["living-nature"], ["environment"], ["forest", "garden"], "community"],
  "k-cousin-camp": ["community-change", ["organize", "negotiate"], ["home"], ["sibling"], "resource-management", ["family"], ["none"], ["community"], ["home", "food"], "family"],
  "k-night-market-lantern": ["rescue", ["travel", "discover"], ["city"], ["outsider"], "journey-encounters", ["family"], ["magic-object"], ["family"], ["journey", "magic"], "family"],
  "k-club-treehouse-election": ["community-change", ["organize", "negotiate"], ["home"], ["organizer"], "community-project", ["community"], ["none"], ["community"], ["food", "home"], "community"],
  "k-whale-song-translator": ["quest", ["explore", "discover"], ["coast"], ["student"], "cause-and-effect-discovery", ["solo"], ["communicating-animal"], ["personal-belonging"], ["sea", "music"], "individual"],
  "k-bug-hotel": ["investigation", ["build", "solve"], ["garden"], ["student"], "cause-and-effect-discovery", ["solo"], ["none"], ["personal-belonging"], ["garden", "animal"], "individual"],
  "k-library-card-quest": ["quest", ["care", "organize"], ["small-town"], ["student"], "escalating-trials", ["community"], ["none"], ["personal-belonging"], ["book", "city", "home"], "individual"],
  "k-stormy-lighthouse-pups": ["rescue", ["care", "protect"], ["coast"], ["caretaker"], "survival-pressure", ["siblings"], ["none"], ["rescue"], ["storm", "animal"], "family"],
  "k-cardboard-castle-siege": ["competition", ["compete", "reconcile"], ["home"], ["sibling"], "rivalry-ladder", ["rivals"], ["none"], ["competition"], ["castle", "storm", "sport"], "team"],
  "k-market-day-mixup": ["community-change", ["organize", "adapt"], ["small-town"], ["worker"], "cause-and-effect-discovery", ["community"], ["magic-object"], ["community"], ["food", "magic"], "community"],
  "k-underground-choir-mice": ["coming-of-age", ["perform", "reconcile"], ["underground"], ["performer"], "creative-process", ["team"], ["communicating-animal"], ["personal-belonging"], ["music", "animal"], "team"],
  "k-summer-lemonade-empire": ["workplace-crisis", ["organize", "build"], ["small-town"], ["sibling"], "resource-management", ["siblings"], ["none"], ["livelihood"], ["food", "city", "home"], "pair"],
  "k-paper-boat-race": ["investigation", ["explore", "solve"], ["small-town"], ["student"], "clue-chain", ["friendship"], ["none"], ["personal-belonging"], ["journey", "mystery"], "team"],
  "k-good-dragon-daycare": ["workplace-crisis", ["care", "teach"], ["workplace"], ["apprentice"], "training-progression", ["mentor-student"], ["mythic-being"], ["livelihood"], ["animal", "magic"], "individual"],
};

const preteens: Record<string, ExpandedMelanieSemanticSeed> = {
  "p-static-radio-friend": ["investigation", ["investigate", "discover"], ["small-town"], ["investigator"], "secret-uncovering", ["solo"], ["time-distortion"], ["truth"], ["signal", "history", "mystery"], "individual"],
  "p-cartography-club": ["investigation", ["explore", "document"], ["small-town"], ["student"], "cause-and-effect-discovery", ["team"], ["prophecy"], ["truth"], ["journey", "mystery"], "team"],
  "p-foster-siblings-garage-band": ["coming-of-age", ["perform", "reconcile"], ["home", "performance"], ["sibling"], "relationship-negotiation", ["found-family"], ["none"], ["relationship"], ["music", "home"], "family"],
  "p-robotics-rivalry": ["competition", ["build", "reconcile"], ["school"], ["student"], "rivalry-ladder", ["rivals"], ["none"], ["competition", "relationship"], ["machine", "school"], "pair"],
  "p-ice-cave-signal": ["rescue", ["investigate", "survive"], ["wilderness"], ["sibling"], "deadline-mission", ["siblings"], ["none"], ["rescue", "family"], ["signal", "mountain"], "pair"],
  "p-carnival-automaton": ["investigation", ["investigate", "discover"], ["performance"], ["investigator"], "cause-and-effect-discovery", ["solo"], ["artificial-intelligence"], ["truth"], ["performance", "machine"], "individual"],
  "p-boarding-pass-mixup": ["coming-of-age", ["travel", "reconcile"], ["transit"], ["traveler"], "relationship-negotiation", ["friendship"], ["none"], ["relationship"], ["journey", "city"], "pair"],
  "p-shipwreck-diary": ["quest", ["explore", "document"], ["coast", "historical"], ["investigator"], "journey-encounters", ["family"], ["none"], ["truth", "legacy"], ["sea", "history"], "family"],
  "p-greenhouse-drone-club": ["creation", ["build", "create"], ["school", "garden"], ["student"], "cause-and-effect-discovery", ["friendship"], ["future-technology"], ["creative-goal"], ["machine", "garden"], "pair"],
  "p-night-swim-team": ["competition", ["compete", "investigate"], ["sports", "small-town"], ["athlete"], "escalating-trials", ["team"], ["none"], ["competition", "truth"], ["sport", "mystery"], "team"],
  "p-storm-shelter-strangers": ["relationship-repair", ["reconcile", "negotiate"], ["small-town"], ["student"], "relationship-negotiation", ["community"], ["none"], ["relationship", "community"], ["storm", "school"], "community"],
  "p-vanishing-orchard": ["quest", ["discover", "care"], ["garden"], ["sibling"], "cause-and-effect-discovery", ["family"], ["time-distortion"], ["family"], ["garden", "magic"], "family"],
  "p-scrap-metal-mech": ["creation", ["build", "reconcile"], ["workplace"], ["sibling"], "creative-process", ["family"], ["none"], ["creative-goal", "family"], ["machine", "city"], "family"],
  "p-echo-canyon-race": ["investigation", ["compete", "investigate"], ["wilderness", "sports"], ["athlete"], "cat-and-mouse", ["rivals"], ["time-distortion"], ["truth", "competition"], ["sport", "signal"], "individual"],
  "p-quarantine-quilt-project": ["community-change", ["create", "organize"], ["school"], ["student"], "community-project", ["community"], ["none"], ["community"], ["art", "school"], "community"],
  "p-comet-scout-camp": ["rescue", ["explore", "rescue"], ["wilderness"], ["leader"], "escalating-trials", ["team"], ["none"], ["rescue", "survival"], ["moon", "forest"], "team"],
  "p-thrift-store-letters": ["investigation", ["investigate", "discover"], ["small-town"], ["investigator"], "clue-chain", ["family"], ["none"], ["truth", "family"], ["history", "book", "mystery"], "family"],
  "p-arcade-ghost-high-score": ["historical-reckoning", ["discover", "document"], ["performance"], ["investigator"], "secret-uncovering", ["community"], ["ghost"], ["legacy"], ["ghost", "mystery"], "community"],
  "p-rescue-dog-academy": ["rescue", ["teach", "rescue"], ["wilderness", "institution"], ["apprentice"], "training-progression", ["mentor-student"], ["none"], ["rescue"], ["animal", "mountain"], "pair"],
  "p-satellite-club-static": ["investigation", ["investigate", "discover"], ["school", "space"], ["student"], "cause-and-effect-discovery", ["team"], ["time-distortion"], ["truth"], ["signal", "space"], "team"],
  "p-family-diner-recipe-war": ["workplace-crisis", ["cook", "negotiate"], ["workplace", "small-town"], ["sibling"], "rivalry-ladder", ["family", "rivals"], ["none"], ["livelihood"], ["food", "city"], "family"],
  "p-abandoned-planetarium": ["quest", ["explore", "discover"], ["institution"], ["student"], "cause-and-effect-discovery", ["friendship"], ["parallel-reality"], ["truth"], ["space", "mystery"], "pair"],
  "p-relay-team-secret": ["ethical-dilemma", ["compete", "hide"], ["school", "sports"], ["athlete"], "escalating-trials", ["team"], ["none"], ["ethical", "competition"], ["sport", "school"], "team"],
  "p-lost-radio-play": ["quest", ["perform", "discover"], ["performance"], ["performer"], "cause-and-effect-discovery", ["team"], ["prophecy"], ["creative-goal"], ["performance", "signal"], "team"],
  "p-storm-drain-explorers": ["quest", ["explore", "discover"], ["underground"], ["student"], "journey-encounters", ["friendship"], ["none"], ["truth", "personal-belonging"], ["mystery", "journey"], "pair"],
  "p-migrant-worker-summer": ["coming-of-age", ["care", "reconcile"], ["garden"], ["friend"], "alternating-perspectives", ["friendship"], ["none"], ["relationship", "family"], ["garden", "food"], "pair"],
  "p-time-trial-bicycle-ghost": ["identity-discovery", ["compete", "discover"], ["wilderness", "sports"], ["athlete"], "rivalry-ladder", ["rivals"], ["ghost"], ["identity", "competition"], ["sport", "ghost"], "individual"],
  "p-lighthouse-inheritance": ["inheritance", ["negotiate", "organize"], ["coast"], ["organizer"], "community-project", ["family"], ["none"], ["legacy", "community"], ["coast", "history"], "family"],
  "p-augmented-scavenger-hunt": ["conspiracy", ["investigate", "explore"], ["city", "digital"], ["student"], "cat-and-mouse", ["friendship"], ["future-technology"], ["truth"], ["signal", "machine"], "pair"],
  "p-quiet-kid-radio-show": ["identity-discovery", ["perform", "teach"], ["school"], ["outsider"], "training-progression", ["solo"], ["none"], ["identity"], ["signal", "school"], "individual"],
  "p-drought-year-well": ["community-change", ["negotiate", "organize"], ["wilderness"], ["organizer"], "resource-management", ["family", "rivals"], ["none"], ["community", "environment"], ["desert", "storm", "mountain"], "community"],
  "p-model-rocket-club-loss": ["community-change", ["build", "organize"], ["school"], ["student"], "training-progression", ["team"], ["none"], ["creative-goal"], ["machine", "science"], "team"],
  "p-antique-shop-mirror": ["quest", ["discover", "care"], ["workplace"], ["apprentice"], "cause-and-effect-discovery", ["family"], ["time-distortion"], ["truth"], ["history", "mystery"], "family"],
  "p-service-dog-training": ["relationship-repair", ["teach", "care"], ["institution"], ["apprentice"], "training-progression", ["mentor-student"], ["none"], ["relationship"], ["animal", "school"], "pair"],
  "p-choir-competition-sabotage": ["investigation", ["investigate", "perform"], ["school", "performance"], ["performer", "investigator"], "cat-and-mouse", ["rivals", "team"], ["none"], ["truth", "competition"], ["music", "mystery"], "team"],
  "p-abandoned-amusement-park": ["quest", ["explore", "escape"], ["performance"], ["student"], "escalating-trials", ["friendship"], ["supernatural-rule"], ["personal-belonging"], ["ghost", "performance"], "team"],
  "p-exchange-student-recipe-box": ["relationship-repair", ["cook", "teach"], ["home"], ["outsider"], "relationship-negotiation", ["found-family"], ["none"], ["relationship"], ["food", "home"], "family"],
  "p-lost-hour-daylight-saving": ["quest", ["explore", "discover"], ["school"], ["student"], "cause-and-effect-discovery", ["team"], ["time-distortion"], ["personal-belonging"], ["clock", "school"], "team"],
  "p-family-farm-drone-survey": ["investigation", ["investigate", "protect"], ["garden"], ["student"], "clue-chain", ["family"], ["none"], ["truth", "family"], ["machine", "mystery"], "family"],
  "p-understudy-lead-role": ["coming-of-age", ["perform", "reconcile"], ["performance", "school"], ["performer"], "relationship-negotiation", ["friendship"], ["none"], ["relationship", "creative-goal"], ["performance", "school"], "pair"],
  "p-coding-camp-ai-pet": ["ethical-dilemma", ["build", "teach"], ["institution"], ["student"], "cause-and-effect-discovery", ["solo"], ["artificial-intelligence"], ["ethical"], ["machine", "science"], "individual"],
  "p-restored-carousel": ["historical-reckoning", ["restore", "discover"], ["performance"], ["apprentice"], "memory-reconstruction", ["mentor-student"], ["memory-technology"], ["legacy"], ["performance", "history"], "pair"],
  "p-cross-country-injury-secret": ["competition", ["compete", "adapt"], ["sports", "school"], ["athlete"], "training-progression", ["team"], ["none"], ["competition", "truth"], ["sport", "school"], "team"],
  "p-lost-decade-postcards": ["identity-discovery", ["discover", "explore"], ["home"], ["outsider"], "secret-uncovering", ["family"], ["none"], ["identity", "truth"], ["history", "home"], "individual"],
  "p-storm-warning-app": ["ethical-dilemma", ["build", "protect"], ["small-town"], ["student"], "cause-and-effect-discovery", ["friendship"], ["future-technology"], ["public-duty", "truth"], ["storm", "signal", "machine"], "pair"],
  "p-summer-job-boardwalk": ["quest", ["discover", "investigate"], ["performance"], ["worker"], "secret-uncovering", ["mentor-student"], ["time-distortion"], ["truth"], ["performance", "mystery"], "pair"],
  "p-quiet-town-mural": ["quest", ["create", "discover"], ["small-town"], ["artist"], "cause-and-effect-discovery", ["community"], ["living-nature"], ["creative-goal"], ["art", "mystery"], "community"],
  "p-siblings-inherited-boat": ["inheritance", ["restore", "discover"], ["coast"], ["sibling"], "memory-reconstruction", ["siblings"], ["none"], ["legacy", "family"], ["sea", "history"], "pair"],
};

const teens: Record<string, ExpandedMelanieSemanticSeed> = {
  "t-static-choir": ["historical-reckoning", ["document", "discover"], ["small-town", "performance"], ["performer"], "cause-and-effect-discovery", ["community"], ["ghost"], ["legacy", "identity"], ["music", "ghost"], "community"],
  "t-debate-team-blackmail": ["conspiracy", ["investigate", "compete"], ["school"], ["student"], "cat-and-mouse", ["rivals"], ["none"], ["truth", "justice"], ["school", "politics"], "individual"],
  "t-ferris-wheel-time-loop": ["second-chance", ["reconcile", "adapt"], ["performance"], ["worker"], "alternating-perspectives", ["romantic-pair"], ["time-distortion"], ["relationship", "ethical"], ["performance", "clock"], "pair"],
  "t-foster-care-road-trip": ["identity-discovery", ["travel", "reconcile"], ["transit"], ["sibling"], "journey-encounters", ["siblings"], ["none"], ["family", "identity"], ["journey", "home"], "pair"],
  "t-drone-journalism-club": ["conspiracy", ["document", "investigate"], ["small-town"], ["student"], "cat-and-mouse", ["family"], ["none"], ["truth", "justice"], ["machine", "politics", "mystery"], "individual"],
  "t-glacier-research-station": ["conspiracy", ["investigate", "survive"], ["wilderness"], ["scientist"], "survival-pressure", ["team"], ["none"], ["truth", "survival"], ["mountain", "science"], "team"],
  "t-second-chance-band-reunion": ["relationship-repair", ["perform", "reconcile"], ["performance", "city"], ["performer"], "relationship-negotiation", ["friendship"], ["none"], ["relationship"], ["music", "city"], "team"],
  "t-underground-fight-club-chess": ["workplace-crisis", ["compete", "escape"], ["underground", "city"], ["student"], "escalating-trials", ["rivals"], ["none"], ["freedom", "competition"], ["city", "machine"], "individual"],
  "t-vanishing-lake-town": ["historical-reckoning", ["discover", "document"], ["historical", "coast"], ["investigator"], "memory-reconstruction", ["family"], ["sentient-place"], ["truth", "legacy"], ["history", "sea"], "individual"],
  "t-hospital-volunteer-ghost-story": ["identity-discovery", ["care", "investigate"], ["institution"], ["caretaker"], "secret-uncovering", ["solo"], ["ghost"], ["truth", "identity"], ["ghost", "home"], "individual"],
  "t-competitive-baking-rivalry-romance": ["competition", ["cook", "compete"], ["school", "workplace"], ["student"], "training-progression", ["rivals", "romantic-pair"], ["none"], ["competition", "relationship"], ["food", "romance"], "pair"],
  "t-refugee-resettlement-soccer": ["coming-of-age", ["compete", "adapt"], ["school", "sports"], ["outsider"], "training-progression", ["team"], ["none"], ["identity", "community"], ["sport", "school"], "team"],
  "t-augmented-reality-grief-app": ["identity-discovery", ["reconcile", "discover"], ["city"], ["student"], "cause-and-effect-discovery", ["family"], ["artificial-intelligence"], ["identity", "relationship"], ["machine", "ghost"], "family"],
  "t-storm-chasing-road-crew": ["identity-discovery", ["travel", "adapt"], ["wilderness", "transit"], ["apprentice"], "training-progression", ["mentor-student"], ["none"], ["identity"], ["storm", "journey"], "pair"],
  "t-boarding-school-secret-society": ["conspiracy", ["investigate", "rebel"], ["institution", "historical"], ["student"], "secret-uncovering", ["rivals"], ["none"], ["justice", "truth"], ["school", "politics", "mystery"], "individual"],
  "t-underwater-salvage-rivalry": ["survival", ["compete", "survive"], ["sea"], ["worker"], "survival-pressure", ["rivals"], ["none"], ["survival", "competition"], ["sea", "machine"], "pair"],
  "t-small-town-closing-factory": ["community-change", ["organize", "rebel"], ["workplace", "small-town"], ["student"], "political-maneuvering", ["family"], ["none"], ["justice", "livelihood"], ["city", "fire"], "community"],
  "t-online-friend-real-life": ["identity-discovery", ["reconcile", "adapt"], ["digital", "city"], ["student"], "relationship-negotiation", ["friendship"], ["none"], ["identity", "relationship"], ["machine", "city"], "pair"],
  "t-migrant-farm-labor-rights": ["community-change", ["organize", "rebel"], ["garden"], ["organizer"], "political-maneuvering", ["community"], ["none"], ["justice"], ["food", "politics", "garden"], "community"],
  "t-abandoned-mall-time-capsule": ["historical-reckoning", ["discover", "document"], ["city"], ["student"], "memory-reconstruction", ["friendship"], ["none"], ["legacy"], ["history", "mystery"], "team"],
  "t-astronomy-club-eclipse-secret": ["ethical-dilemma", ["travel", "reconcile"], ["transit"], ["student"], "relationship-negotiation", ["friendship"], ["none"], ["truth", "ethical"], ["moon", "journey"], "team"],
  "t-competitive-debate-immigrant-family": ["coming-of-age", ["compete", "reconcile"], ["school"], ["student"], "moral-choice", ["family"], ["none"], ["identity", "family"], ["school", "politics"], "family"],
  "t-drowned-orchestra-pit": ["historical-reckoning", ["create", "perform"], ["performance"], ["performer", "artist"], "creative-process", ["team"], ["sentient-place"], ["legacy", "creative-goal"], ["music", "sea"], "team"],
  "t-street-art-anonymous-rival": ["identity-discovery", ["create", "investigate"], ["city"], ["artist"], "cat-and-mouse", ["rivals"], ["none"], ["identity", "creative-goal"], ["art", "city"], "pair"],
  "t-wilderness-therapy-program": ["coming-of-age", ["adapt", "reconcile"], ["wilderness"], ["survivor"], "training-progression", ["mentor-student"], ["none"], ["identity"], ["mountain", "forest"], "pair"],
  "t-esports-team-burnout": ["ethical-dilemma", ["compete", "adapt"], ["digital", "city"], ["athlete"], "escalating-trials", ["team"], ["none"], ["identity", "competition"], ["machine", "sport"], "team"],
  "t-small-plane-crash-survival": ["survival", ["survive", "reconcile"], ["wilderness"], ["survivor"], "survival-pressure", ["rivals"], ["none"], ["survival"], ["mountain", "storm"], "team"],
  "t-underground-radio-pirate": ["community-change", ["rebel", "organize"], ["small-town"], ["rebel"], "political-maneuvering", ["solo"], ["none"], ["community", "freedom"], ["signal", "politics"], "individual"],
  "t-competitive-figure-skating-injury": ["competition", ["compete", "reconcile"], ["sports"], ["athlete"], "rivalry-ladder", ["rivals"], ["none"], ["competition"], ["sport", "music"], "pair"],
  "t-city-blackout-strangers": ["relationship-repair", ["reconcile", "negotiate"], ["city"], ["outsider"], "relationship-negotiation", ["romantic-pair", "community"], ["none"], ["relationship"], ["city", "romance"], "community"],
  "t-inherited-letters-vietnam": ["historical-reckoning", ["document", "discover"], ["home", "historical"], ["student"], "alternating-perspectives", ["intergenerational"], ["none"], ["legacy", "truth"], ["history", "book"], "family"],
  "t-hacker-collective-whistleblower": ["ethical-dilemma", ["rebel", "investigate"], ["digital", "city"], ["rebel"], "moral-choice", ["team"], ["artificial-intelligence"], ["ethical", "justice"], ["machine", "politics"], "team"],
  "t-competitive-marching-band-family": ["coming-of-age", ["perform", "care"], ["school"], ["performer"], "moral-choice", ["family", "team"], ["none"], ["family", "competition"], ["music", "school"], "family"],
  "t-search-and-rescue-teen-volunteer": ["rescue", ["rescue", "adapt"], ["wilderness"], ["apprentice"], "deadline-mission", ["mentor-student"], ["none"], ["rescue"], ["mountain", "signal"], "individual"],
  "t-time-capsule-graduation-promise": ["coming-of-age", ["discover", "reconcile"], ["school"], ["student"], "memory-reconstruction", ["friendship"], ["none"], ["relationship", "legacy"], ["school", "history"], "team"],
  "t-competitive-orchard-cider-rivals": ["community-change", ["organize", "adapt"], ["garden", "small-town"], ["worker"], "resource-management", ["rivals"], ["none"], ["livelihood", "community"], ["garden", "romance"], "pair"],
  "t-deep-web-missing-persons": ["rescue", ["investigate", "rescue"], ["digital", "city"], ["outsider"], "procedural-problem-solving", ["solo"], ["none"], ["rescue", "truth"], ["mystery", "machine"], "individual"],
  "t-competitive-slam-poetry": ["coming-of-age", ["perform", "reconcile"], ["school", "performance"], ["artist"], "creative-process", ["solo"], ["none"], ["identity", "creative-goal"], ["art", "performance"], "individual"],
  "t-abandoned-mine-town-legend": ["survival", ["explore", "survive"], ["underground", "historical"], ["outsider"], "escalating-trials", ["friendship"], ["supernatural-rule"], ["survival"], ["ghost", "mountain", "history"], "team"],
  "t-competitive-college-essay-cheating": ["ethical-dilemma", ["reconcile", "hide"], ["school"], ["student"], "moral-choice", ["friendship"], ["none"], ["ethical"], ["school", "book"], "pair"],
  "t-summer-lifeguard-near-miss": ["ethical-dilemma", ["protect", "adapt"], ["coast"], ["apprentice"], "moral-choice", ["mentor-student"], ["none"], ["ethical", "identity"], ["sea", "coast"], "individual"],
  "t-underground-punk-scene-legacy": ["inheritance", ["organize", "reconcile"], ["city", "underground"], ["artist"], "community-project", ["found-family"], ["none"], ["legacy", "community"], ["music", "city"], "community"],
  "t-competitive-robotics-sabotage-rivalry": ["conspiracy", ["investigate", "build"], ["school"], ["student"], "cat-and-mouse", ["team"], ["none"], ["truth", "competition"], ["machine", "school"], "team"],
  "t-witness-protection-new-school": ["identity-discovery", ["hide", "adapt"], ["school", "small-town"], ["outsider"], "survival-pressure", ["solo"], ["none"], ["identity", "survival"], ["school", "mystery"], "individual"],
  "t-competitive-open-water-swim-loss": ["second-chance", ["compete", "reconcile"], ["sea", "sports"], ["athlete"], "escalating-trials", ["family"], ["none"], ["identity", "competition"], ["sea", "sport"], "individual"],
  "t-community-theater-closing-season": ["community-change", ["perform", "organize"], ["performance"], ["performer"], "community-project", ["team"], ["none"], ["community", "creative-goal"], ["performance", "history"], "community"],
  "t-cyberbullying-anonymous-account": ["investigation", ["investigate", "protect"], ["school", "digital"], ["student"], "secret-uncovering", ["friendship"], ["none"], ["justice", "truth"], ["machine", "school"], "pair"],
  "t-competitive-chess-immigrant-prodigy": ["coming-of-age", ["compete", "negotiate"], ["city"], ["student"], "relationship-negotiation", ["parent-child"], ["none"], ["identity", "freedom"], ["city", "politics"], "family"],
};

const adult: Record<string, ExpandedMelanieSemanticSeed> = {
  "a-cartographer-marriage": ["second-chance", ["reconcile", "discover"], ["home", "historical"], ["parent"], "relationship-negotiation", ["family", "romantic-pair"], ["sentient-place"], ["relationship", "family"], ["castle", "moon", "history"], "family"],
  "a-forensic-accountant-cult": ["conspiracy", ["investigate", "document"], ["institution"], ["investigator"], "clue-chain", ["solo"], ["none"], ["truth", "justice"], ["archive", "politics"], "individual"],
  "a-lighthouse-keepers-affair": ["historical-reckoning", ["document", "reconcile"], ["coast"], ["caretaker"], "memory-reconstruction", ["family"], ["none"], ["truth", "relationship"], ["coast", "romance"], "family"],
  "a-vintner-inheritance-dispute": ["inheritance", ["negotiate", "reconcile"], ["garden"], ["sibling"], "relationship-negotiation", ["siblings"], ["none"], ["legacy", "family"], ["garden", "food"], "family"],
  "a-retired-spy-book-club": ["conspiracy", ["negotiate", "hide"], ["small-town"], ["survivor"], "political-maneuvering", ["community"], ["none"], ["truth", "legacy"], ["book", "politics"], "community"],
  "a-drought-town-water-rights": ["ethical-dilemma", ["negotiate", "protect"], ["small-town"], ["worker"], "moral-choice", ["community"], ["none"], ["ethical", "community"], ["desert", "politics"], "community"],
  "a-restoration-architect-haunted-theater": ["workplace-crisis", ["restore", "investigate"], ["performance", "institution"], ["artist"], "escalating-trials", ["solo"], ["sentient-place"], ["creative-goal"], ["performance", "ghost"], "individual"],
  "a-competing-obituary-writers": ["second-chance", ["document", "reconcile"], ["workplace", "small-town"], ["worker"], "relationship-negotiation", ["rivals"], ["none"], ["relationship", "legacy"], ["book", "romance"], "pair"],
  "a-deep-sea-cable-repair-crew": ["survival", ["survive", "discover"], ["sea"], ["worker"], "survival-pressure", ["team"], ["none"], ["survival", "truth"], ["sea", "machine"], "team"],
  "a-competitive-antique-dealers": ["investigation", ["investigate", "negotiate"], ["city", "workplace"], ["worker"], "cat-and-mouse", ["rivals"], ["none"], ["truth"], ["history", "art"], "pair"],
  "a-hospice-nurse-last-requests": ["ethical-dilemma", ["care", "reconcile"], ["institution"], ["caretaker"], "moral-choice", ["solo"], ["none"], ["ethical", "identity"], ["home", "history"], "individual"],
  "a-failed-startup-founders-reunion": ["relationship-repair", ["reconcile", "negotiate"], ["workplace", "city"], ["worker"], "relationship-negotiation", ["colleagues"], ["none"], ["relationship", "legacy"], ["machine", "city"], "community"],
  "a-migrating-shepherd-family-land": ["inheritance", ["travel", "adapt"], ["wilderness"], ["caretaker"], "resource-management", ["family"], ["none"], ["legacy", "livelihood"], ["animal", "journey"], "family"],
  "a-cold-case-detective-retirement": ["investigation", ["investigate", "solve"], ["city"], ["investigator"], "clue-chain", ["solo"], ["none"], ["justice", "truth"], ["mystery", "city"], "individual"],
  "a-competitive-orchestra-conductor-succession": ["competition", ["perform", "negotiate"], ["performance"], ["artist"], "rivalry-ladder", ["rivals"], ["none"], ["competition", "legacy"], ["music", "performance"], "pair"],
  "a-off-grid-homestead-inheritance": ["inheritance", ["adapt", "discover"], ["wilderness"], ["outsider"], "resource-management", ["solo"], ["none"], ["legacy", "identity"], ["home", "forest"], "individual"],
  "a-competing-food-truck-owners": ["relationship-repair", ["cook", "negotiate"], ["city"], ["worker"], "rivalry-ladder", ["rivals", "romantic-pair"], ["none"], ["livelihood", "relationship"], ["food", "romance"], "pair"],
  "a-retired-astronaut-memoir-ghostwriter": ["conspiracy", ["document", "discover"], ["small-town"], ["scholar"], "alternating-perspectives", ["solo"], ["none"], ["truth", "legacy"], ["space", "archive"], "individual"],
  "a-competing-vineyard-harvest-storm": ["relationship-repair", ["protect", "organize"], ["garden"], ["worker"], "deadline-mission", ["rivals"], ["none"], ["livelihood", "relationship"], ["garden", "storm"], "community"],
  "a-small-press-editor-manuscript": ["conspiracy", ["discover", "investigate"], ["workplace"], ["worker"], "secret-uncovering", ["solo"], ["none"], ["truth", "legacy"], ["book", "archive", "mystery"], "individual"],
  "a-competitive-marathon-comeback-age": ["second-chance", ["compete", "adapt"], ["city", "sports"], ["athlete"], "training-progression", ["solo"], ["none"], ["identity", "competition"], ["sport", "city"], "individual"],
  "a-family-run-funeral-home-succession": ["inheritance", ["care", "reconcile"], ["workplace", "small-town"], ["caretaker"], "relationship-negotiation", ["family"], ["none"], ["legacy", "family"], ["home", "history"], "family"],
  "a-competing-real-estate-developers-town": ["conspiracy", ["negotiate", "hide"], ["city"], ["worker"], "cat-and-mouse", ["rivals"], ["none"], ["truth", "livelihood"], ["city", "politics"], "pair"],
  "a-competitive-beekeepers-county-fair": ["relationship-repair", ["compete", "reconcile"], ["garden", "small-town"], ["worker"], "rivalry-ladder", ["rivals", "family"], ["none"], ["relationship", "competition"], ["garden", "animal"], "family"],
  "a-retired-diplomat-memoir-secrets": ["conspiracy", ["document", "negotiate"], ["political", "institution"], ["leader"], "political-maneuvering", ["solo"], ["none"], ["truth", "political"], ["politics", "archive"], "individual"],
  "a-competing-lighthouse-restoration-grant": ["competition", ["negotiate", "organize"], ["coast"], ["organizer"], "rivalry-ladder", ["rivals"], ["none"], ["community", "legacy"], ["coast", "history"], "community"],
  "a-cold-storage-warehouse-mystery": ["conspiracy", ["investigate", "document"], ["workplace"], ["worker"], "clue-chain", ["solo"], ["none"], ["truth", "political"], ["archive", "mystery"], "individual"],
  "a-competing-radio-hosts-late-night": ["relationship-repair", ["perform", "reconcile"], ["workplace"], ["performer"], "alternating-perspectives", ["rivals", "romantic-pair"], ["none"], ["relationship", "identity"], ["signal", "romance", "performance"], "pair"],
  "a-competing-family-orchards-drought-year": ["relationship-repair", ["negotiate", "adapt"], ["garden"], ["worker"], "resource-management", ["family", "rivals"], ["none"], ["livelihood", "family"], ["garden", "desert"], "family"],
  "a-retired-detective-memoir-cold-case": ["conspiracy", ["document", "investigate"], ["city"], ["investigator"], "secret-uncovering", ["solo"], ["none"], ["justice", "truth"], ["mystery", "archive"], "individual"],
  "a-competing-museum-curators-artifact": ["investigation", ["investigate", "document"], ["institution"], ["scholar"], "procedural-problem-solving", ["rivals"], ["none"], ["truth", "legacy"], ["history", "art", "mystery"], "pair"],
  "a-family-diner-closing-generations": ["relationship-repair", ["cook", "reconcile"], ["workplace"], ["caretaker"], "relationship-negotiation", ["family", "intergenerational"], ["none"], ["family", "legacy"], ["food", "home"], "family"],
  "a-competing-shipwreck-salvage-crews": ["competition", ["compete", "discover"], ["sea"], ["worker"], "rivalry-ladder", ["rivals"], ["none"], ["ethical", "competition"], ["sea", "history"], "team"],
  "a-retired-teacher-former-student-reunion": ["relationship-repair", ["teach", "reconcile"], ["small-town"], ["teacher"], "relationship-negotiation", ["mentor-student"], ["none"], ["relationship", "legacy"], ["school", "history"], "pair"],
  "a-competing-craft-brewery-founders": ["workplace-crisis", ["negotiate", "reconcile"], ["workplace", "city"], ["worker"], "relationship-negotiation", ["rivals", "colleagues"], ["none"], ["livelihood", "relationship"], ["food", "city"], "pair"],
  "a-remote-weather-station-isolation": ["survival", ["survive", "adapt"], ["wilderness"], ["scientist"], "survival-pressure", ["solo"], ["none"], ["survival", "identity"], ["science", "storm", "mountain"], "individual"],
  "a-competing-family-bakeries-holiday-order": ["relationship-repair", ["cook", "negotiate"], ["small-town"], ["worker"], "relationship-negotiation", ["rivals"], ["none"], ["relationship", "livelihood"], ["food", "city"], "community"],
  "a-cold-war-era-declassified-letters": ["conspiracy", ["investigate", "document"], ["archive", "political"], ["scholar"], "procedural-problem-solving", ["intergenerational"], ["none"], ["truth", "justice"], ["archive", "politics"], "individual"],
  "a-competing-vineyard-heirs-wedding": ["relationship-repair", ["negotiate", "reconcile"], ["garden"], ["sibling"], "relationship-negotiation", ["family", "romantic-pair"], ["none"], ["family", "relationship"], ["garden", "romance"], "family"],
  "a-competing-search-rescue-volunteer-crews": ["rescue", ["rescue", "negotiate"], ["wilderness"], ["worker"], "procedural-problem-solving", ["rivals", "team"], ["none"], ["rescue"], ["mountain", "storm"], "team"],
  "a-retiring-judge-final-case": ["ethical-dilemma", ["document", "reconcile"], ["institution", "small-town"], ["leader"], "moral-choice", ["solo"], ["none"], ["justice", "ethical"], ["politics", "history"], "individual"],
  "a-competing-restaurant-critics-anonymous": ["identity-discovery", ["document", "discover"], ["city"], ["worker"], "secret-uncovering", ["romantic-pair", "rivals"], ["none"], ["identity", "relationship"], ["food", "romance", "city"], "pair"],
  "a-competing-genealogists-family-plot": ["investigation", ["investigate", "document"], ["archive"], ["scholar"], "clue-chain", ["rivals"], ["none"], ["truth", "justice"], ["history", "archive"], "pair"],
  "a-retired-firefighter-cold-case-arson": ["conspiracy", ["investigate", "protect"], ["small-town"], ["survivor"], "procedural-problem-solving", ["solo"], ["none"], ["truth", "community"], ["fire", "mystery"], "individual"],
  "a-competing-orchard-cider-mill-succession": ["workplace-crisis", ["negotiate", "adapt"], ["workplace", "small-town"], ["worker"], "relationship-negotiation", ["family"], ["none"], ["livelihood", "legacy"], ["garden", "food"], "family"],
  "a-competing-marine-biologists-reef-survey": ["relationship-repair", ["investigate", "reconcile"], ["sea"], ["scientist"], "relationship-negotiation", ["rivals"], ["none"], ["relationship", "environment"], ["sea", "science"], "pair"],
  "a-family-owned-print-shop-closing": ["inheritance", ["organize", "reconcile"], ["workplace", "small-town"], ["caretaker"], "community-project", ["family"], ["none"], ["legacy", "community"], ["book", "history", "machine"], "community"],
  "a-competing-lighthouse-keepers-logbooks": ["investigation", ["document", "investigate"], ["coast", "archive"], ["scholar"], "alternating-perspectives", ["rivals"], ["none"], ["legacy", "truth"], ["coast", "history"], "individual"],
};

export const EXPANDED_MELANIE_SEMANTIC_SEEDS = {
  kids,
  preteens,
  teens,
  adult,
} satisfies Record<string, Record<string, ExpandedMelanieSemanticSeed>>;
