// /screens/recommenders/types.ts
export type EngineId = "googleBooks" | "openLibrary" | "kitsu" | "comicVine";
export type DomainMode = "default" | "picture" | "earlyReader" | "chapterMiddle";
export type DeckKey = "k2" | "36" | "ms_hs" | "adult";
export type TagCounts = Record<string, number>;
export type TasteAxis = "warmth" | "darkness" | "humor" | "complexity" | "characterFocus" | "pacing" | "ideaDensity" | "realism";
export type TasteProfile = { axes: Partial<Record<TasteAxis, number>>; confidence?: number; };
export type CommercialSignals = {
  bestseller?: boolean;
  awards?: number;
  popularityTier?: number;
  sourceCount?: number;
};
export type RecommendationDoc = { key?: string; id?: string; title?: string; author_name?: string[]; first_publish_year?: number; cover_i?: number | string; subject?: string[]; subtitle?: string; description?: string; edition_count?: number; language?: string[]; ebook_access?: string; commercialSignals?: CommercialSignals; };
export type RecommendationItem = { kind: "open_library"; doc: RecommendationDoc; };
export type RecommendationResult = {
  gcdAdapterStatus?: "ok" | "proxy_403" | "proxy_error" | "disabled";
  debugRungStats?: RungDiagnostics;
  debugSourceStats?: Record<string, { rawFetched: number; postFilterCandidates: number; finalSelected: number; }>;
  debugCandidatePool?: any[];
  debugRawPool?: any[];
  debugFilterAudit?: any[];
  debugFilterAuditSummary?: { kept: number; rejected: number; reasons: Record<string, number>; };
  debugFinalRecommender?: {
    inputCount: number;
    dedupedCount: number;
    acceptedCount: number;
    rejectedCount: number;
    rejectionCounts: Record<string, number>;
    rejected: Array<{ id: string; title: string; author: string; source: EngineId; reason: string; detail?: string; }>;
  };
  sourceEnabled?: RecommendationSourceDiagnostics;
  sourceSkippedReason?: string[];
  debugRouterVersion?: string;
  deploymentRuntimeMarker?: string;
  debugGcdDispatchTrace?: {
    sourceEnabledComicVine: boolean;
    traceSource?: "router" | "fallback" | "report-default";
    includeGcd: boolean;
    comicVineEnvVarPresent?: boolean;
    comicVineKeyDetected?: boolean;
    comicVineEnabledRuntime?: boolean;
    runtimePlatform?: "client" | "server";
    runtimeEnvironment?: "client_like" | "server_like";
    comicVineEnvKeyLength?: number;
    comicVineProxyUrl?: string;
    normalizedComicVineProxyUrl?: string;
    comicVineProxyConfigured?: boolean;
    comicVineProxyHealthStatus?: "ok" | "failed" | "unknown";
    comicVineProxyErrorBody?: string;
    kitsuEligibleFromSwipes?: boolean;
    likedAnimeMangaCount?: number;
    skippedAnimeMangaCount?: number;
    buildComicVineFacetRungsCalled: boolean;
    kitsuRungsLength?: number;
    comicVineRungsLength: number;
    mainRungQueriesLength: number;
    kitsuFetchAttempted?: boolean;
    gcdFetchAttempted: boolean;
    comicVineFetchAttempted?: boolean;
    kitsuQueryTexts?: string[];
    gcdQueryTexts?: string[];
    comicVineRungsBuilt?: string[];
    comicVineQueriesActuallyFetched?: string[];
    gcdFetchResults?: Array<{ query: string; status: string; rawCount: number; error: string | null }>;
    comicVineResolvedSeedQuery?: string;
    comicVineFallbackReason?: string;
    comicVineUsedFallbackQuery?: boolean;
    comicVinePositiveQueries?: string[];
    comicVineExcludedTermsAppliedInFilterOnly?: boolean;
    comicVineQueryTooLong?: boolean;
  };
  debugComicVineDispatchTrace?: RecommendationResult["debugGcdDispatchTrace"];
  finalAcceptedDocsLength?: number;
  renderedTopRecommendationsLength?: number;
  teenPostPassOutputTitles?: string[];
  finalItemsLength?: number;
  finalItemsTitles?: string[];
  returnedItemsLength?: number;
  returnedItemsTitles?: string[];
  teenPostPassInputLength?: number;
  teenPostPassOutputLength?: number;
  droppedBeforeRenderReason?: string;
  teenPostPassInputSource?: string;
  scoredCandidateUniverseCount?: number;
  convertedDocsAvailableForScoringCount?: number;
  gcdStructuralEnrichmentCount?: number;
  gcdEntryPointLikeCount?: number;
  gcdCollectedLikeCount?: number;
  gcdIssueLikeCount?: number;
  scoredCandidateUniverseSources?: Record<string, number>;
  scoredCandidateUniverseFranchiseRoots?: string[];
  broadArtifactRejectedTitles?: string[];
  zeroScoreBroadFillersUsed?: number;
  entitySeedCandidatesFoundBySeed?: Record<string, number>;
  entitySeedCandidatesSelected?: string[];
  parentFranchiseRootByTitle?: Record<string, string>;
  sideArcRejectedTitles?: string[];
  selectedParentFranchiseCounts?: Record<string, number>;
  duplicateTitleRejectedTitles?: string[];
  negativeScoreRejectedTitles?: string[];
  untranslatedEditionRejectedTitles?: string[];
  semanticBreadthSelections?: string[];
  adjacentSeedExpansionCandidates?: string[];
  seedSaturationPenaltyApplied?: Record<string, number>;
  selectedFranchiseRoots?: string[];
  profileSelectedEntitySeeds?: string[];
  suppressedGlobalSeedReason?: string;
  scoredUniverseFailure?: boolean;
  scoredUniverseFailureReason?: string;
  scoredUniversePreviewTitles?: string[];
  finalRankedDocsBaseLength?: number;
  rankedDocsLength?: number;
  filterKeptDocsLength?: number;
  filterKeptDocsTitles?: string[];
  candidatePoolInputLength?: number;
  candidatePoolDropReasons?: Array<{ title: string; reason: string }>;
  rankedInputLength?: number;
  rankedDropReasons?: Array<{ title: string; reason: string }>;
  shapedInputLength?: number;
  shapedDropReasons?: Array<{ title: string; reason: string }>;
  normalizedDocsCount?: number;
  postCanonicalizationCount?: number;
  postDeduplicationCount?: number;
  postAuthorityFilterCount?: number;
  postLaneFilterCount?: number;
  postShapeGateCount?: number;
  postFinalShapingCount?: number;
  finalRecommenderInputCount?: number;
  stageDropReasons?: Record<string, Record<string, number>>;
  preTopUpFinalItemsLength?: number;
  topUpCandidatesConsideredLength?: number;
  topUpCandidatesAcceptedLength?: number;
  topUpRejectedReasons?: Record<string, number>;
  topUpSourceRankedDocsLength?: number;
  topUpSourceCandidateDocsLength?: number;
  topUpSourceNormalizedCandidatesLength?: number;
  topUpSourceEnrichedDocsLength?: number;
  topUpSourceDebugRawPoolLength?: number;
  topUpMergedPoolBeforeFiltersLength?: number;
  topUpMergedPoolAfterDedupeLength?: number;
  topUpMergedPoolAfterQualityFiltersLength?: number;
  topUpQualityRejectedReasons?: Record<string, number>;
  topUpQualityRejectedTitlesByReason?: Record<string, string[]>;
  entitySeedConvertedCount?: number;
  entitySeedTopUpEligibleCount?: number;
  entitySeedTopUpRejectedReasons?: Record<string, number>;
  entitySeedTopUpRejectedTitlesByReason?: Record<string, string[]>;
  postTopUpFinalItemsLength?: number;
  returnedItemsBuiltFrom?: string;
  recoveryTriggered?: boolean;
  recoveryInputPoolLength?: number;
  recoveryEntitySeedMatches?: number;
  recoveryRejectedReasons?: Record<string, number>;
  recoveryFinalItemsLength?: number;
  countContractSatisfied?: boolean;
  finalEligibleNonNegativeCount?: number;
  countContractShortfallReason?: string;
  usedEmergencyFallback?: boolean;
  fallbackReason?: string;
  fallbackSource?: string;
  preFallbackCandidateCount?: number;
  preFallbackRankedCount?: number;
  preFallbackAcceptedCount?: number;
  finalAcceptedDocsSource?: string;
  finalAcceptedDocsTitles?: string[];
  finalRankedDocsBaseTitles?: string[];
  rankedDocsTitles?: string[];
  routerResultTracePresent?: boolean;
  routerResultKeys?: string[];
  engineId: EngineId;
  engineLabel: string;
  deckKey: DeckKey;
  domainMode?: DomainMode;
  builtFromQuery: string;
  items: RecommendationItem[];
};
export type RecommenderProfileOverride = Record<string, number | undefined>;
export type SourceEnabledConfig = {
  googleBooks?: boolean;
  openLibrary?: boolean;
  localLibrary?: boolean;
  kitsu?: boolean;
  comicVine?: boolean;
};
export type StructuredFetchRung = { rung: number; family?: string; primary: string | null; secondary: string | null; themes: string[]; audience: string; query: string; };
export type BucketPlan = { queries?: string[]; rungs?: StructuredFetchRung[]; bucketId?: string; domainMode?: DomainMode; preview?: string; strategy?: string; signals?: { genres?: string[]; tones?: string[]; textures?: string[]; scenarios?: string[]; }; };
export type RecommenderInput = { deckKey: DeckKey; tagCounts: TagCounts; tasteProfile?: TasteProfile; limit?: number; timeoutMs?: number; minCandidateFloor?: number; bucketPlan?: BucketPlan; domainModeOverride?: DomainMode; profileOverride?: RecommenderProfileOverride; priorRecommendedIds?: string[]; priorRecommendedKeys?: string[]; priorAuthors?: string[]; priorSeriesKeys?: string[]; priorRejectedIds?: string[]; priorRejectedKeys?: string[]; sourceEnabled?: SourceEnabledConfig; localLibrarySupported?: boolean; };


export type RungDiagnostics = {
  byRung: Record<string, number>;
  byRungSource: Record<string, Record<string, number>>;
  total: number;
};

export type RecommendationSourceDiagnostics = {
  googleBooks: boolean;
  openLibrary: boolean;
  localLibrary: boolean;
  kitsu: boolean;
  comicVine: boolean;
};
