export const swipeCardFallbackImages = {
  "adult": {
    "12 Years a Slave": require("./images/adult__12-years-a-slave.jpg"),
    "99% Invisible": require("./images/adult__99-invisible.jpg"),
    "A Court of Thorns and Roses": require("./images/adult__a-court-of-thorns-and-roses.jpg"),
    "Against the Rules with Michael Lewis": require("./images/adult__against-the-rules-with-michael-lewis.jpg"),
    "Alan Wake 2": require("./images/adult__alan-wake-2.jpg"),
    "Alice Isn't Dead": require("./images/adult__alice-isnt-dead.jpg"),
    "Andor": require("./images/adult__andor.jpg"),
    "Annihilation": require("./images/adult__annihilation.jpg"),
    "Archive 81": require("./images/adult__archive-81.jpg"),
    "Arrival": require("./images/adult__arrival.jpg"),
    "Baldur's Gate 3": require("./images/adult__baldurs-gate-3.jpg"),
    "Better Call Saul": require("./images/adult__better-call-saul.jpg"),
    "Big Little Lies": require("./images/adult__big-little-lies.jpg"),
    "Black Mirror": require("./images/adult__black-mirror.jpg"),
    "Blade Runner 2049": require("./images/adult__blade-runner-2049.jpg"),
    "Breaking Bad": require("./images/adult__breaking-bad.jpg"),
    "Bridgerton": require("./images/adult__bridgerton.jpg"),
    "Celeste": require("./images/adult__celeste.jpg"),
    "Chernobyl": require("./images/adult__chernobyl.jpg"),
    "Children of Men": require("./images/adult__children-of-men.jpg"),
    "Circe": require("./images/adult__circe.jpg"),
    "Cloud Atlas": require("./images/adult__cloud-atlas.jpg"),
    "Control": require("./images/adult__control.jpg"),
    "Criminal": require("./images/adult__criminal.jpg"),
    "Cyberpunk 2077": require("./images/adult__cyberpunk-2077.jpg"),
    "Dan Carlin's Hardcore History": require("./images/adult__dan-carlins-hardcore-history.jpg"),
    "Dark": require("./images/adult__dark.jpg"),
    "Dark Matter": require("./images/adult__dark-matter.jpg"),
    "Dead Eyes": require("./images/adult__dead-eyes.jpg"),
    "Death Stranding": require("./images/adult__death-stranding.jpg"),
    "Detroit: Become Human": require("./images/adult__detroit-become-human.jpg"),
    "Disco Elysium": require("./images/adult__disco-elysium.jpg"),
    "Dragon Age: Inquisition": require("./images/adult__dragon-age-inquisition.jpg"),
    "EA Sports FC 24": require("./images/adult__ea-sports-fc-24.jpg"),
    "Elden Ring": require("./images/adult__elden-ring.jpg"),
    "Eternal Sunshine of the Spotless Mind": require("./images/adult__eternal-sunshine-of-the-spotless-mind.jpg"),
    "Everything Everywhere All at Once": require("./images/adult__everything-everywhere-all-at-once.jpg"),
    "Ex Machina": require("./images/adult__ex-machina.jpg"),
    "Fargo": require("./images/adult__fargo.jpg"),
    "Field of Dreams": require("./images/adult__field-of-dreams.jpg"),
    "Fight Club": require("./images/adult__fight-club.jpg"),
    "Firewatch": require("./images/adult__firewatch.jpg"),
    "Friday Night Lights": require("./images/adult__friday-night-lights.jpg"),
    "Game of Thrones": require("./images/adult__game-of-thrones.jpg"),
    "Get Out": require("./images/adult__get-out.jpg"),
    "Ghost of Tsushima": require("./images/adult__ghost-of-tsushima.jpg"),
    "God of War": require("./images/adult__god-of-war.jpg"),
    "Gone Girl": require("./images/adult__gone-girl.jpg"),
    "Hades": require("./images/adult__hades.jpg"),
    "Hardcore History: Addendum": require("./images/adult__hardcore-history-addendum.jpg"),
    "Heavyweight": require("./images/adult__heavyweight.jpg"),
    "Her": require("./images/adult__her.jpg"),
    "Hollow Knight": require("./images/adult__hollow-knight.jpg"),
    "Inception": require("./images/adult__inception.jpg"),
    "Journey": require("./images/adult__journey.jpg"),
    "LeVar Burton Reads": require("./images/adult__levar-burton-reads.jpg"),
    "Life Is Strange": require("./images/adult__life-is-strange.jpg"),
    "Lore": require("./images/adult__lore.jpg"),
    "Mad Max: Fury Road": require("./images/adult__mad-max-fury-road.jpg"),
    "Mass Effect Legendary Edition": require("./images/adult__mass-effect-legendary-edition.jpg"),
    "Mindhunter": require("./images/adult__mindhunter.jpg"),
    "MLB The Show 24": require("./images/adult__mlb-the-show-24.jpg"),
    "Moonlight": require("./images/adult__moonlight.jpg"),
    "My Favorite Murder": require("./images/adult__my-favorite-murder.jpg"),
    "No Country for Old Men": require("./images/adult__no-country-for-old-men.jpg"),
    "Normal Gossip": require("./images/adult__normal-gossip.jpg"),
    "Normal People": require("./images/adult__normal-people.jpg"),
    "Ologies": require("./images/adult__ologies.jpg"),
    "Outer Wilds": require("./images/adult__outer-wilds.jpg"),
    "Outlander": require("./images/adult__outlander.jpg"),
    "Pan's Labyrinth": require("./images/adult__pans-labyrinth.jpg"),
    "Parasite": require("./images/adult__parasite.jpg"),
    "Peaky Blinders": require("./images/adult__peaky-blinders.jpg"),
    "Penny Dreadful": require("./images/adult__penny-dreadful.jpg"),
    "Philosophize This!": require("./images/adult__philosophize-this.jpg"),
    "Portal 2": require("./images/adult__portal-2.jpg"),
    "Prisoners": require("./images/adult__prisoners.jpg"),
    "Project Hail Mary": require("./images/adult__project-hail-mary.jpg"),
    "Radiolab": require("./images/adult__radiolab.jpg"),
    "Rebecca": require("./images/adult__rebecca.jpg"),
    "Red Dead Redemption 2": require("./images/adult__red-dead-redemption-2.jpg"),
    "Reply All": require("./images/adult__reply-all.jpg"),
    "Resident Evil 4": require("./images/adult__resident-evil-4.jpg"),
    "S-Town": require("./images/adult__s-town.jpg"),
    "Severance": require("./images/adult__severance.jpg"),
    "Shōgun": require("./images/adult__shogun.jpg"),
    "Silent Hill 2": require("./images/adult__silent-hill-2.jpg"),
    "Spotlight": require("./images/adult__spotlight.jpg"),
    "Stardew Valley": require("./images/adult__stardew-valley.jpg"),
    "Station Eleven": require("./images/adult__station-eleven.jpg"),
    "Stranger Things": require("./images/adult__stranger-things.jpg"),
    "Stuff You Should Know": require("./images/adult__stuff-you-should-know.jpg"),
    "Subnautica": require("./images/adult__subnautica.jpg"),
    "The Adventure Zone": require("./images/adult__the-adventure-zone.jpg"),
    "The Amelia Project": require("./images/adult__the-amelia-project.jpg"),
    "The Americans": require("./images/adult__the-americans.jpg"),
    "The Bear": require("./images/adult__the-bear.jpg"),
    "The Crown": require("./images/adult__the-crown.jpg"),
    "The Daily": require("./images/adult__the-daily.jpg"),
    "The Departed": require("./images/adult__the-departed.jpg"),
    "The Expanse": require("./images/adult__the-expanse.jpg"),
    "The Girl with the Dragon Tattoo": require("./images/adult__the-girl-with-the-dragon-tattoo.jpg"),
    "The Godfather": require("./images/adult__the-godfather.jpg"),
    "The Goldfinch": require("./images/adult__the-goldfinch.jpg"),
    "The Good Place": require("./images/adult__the-good-place.jpg"),
    "The Grand Budapest Hotel": require("./images/adult__the-grand-budapest-hotel.jpg"),
    "The Haunting of Hill House": require("./images/adult__the-haunting-of-hill-house.jpg"),
    "The History of Rome": require("./images/adult__the-history-of-rome.jpg"),
    "The House in the Cerulean Sea": require("./images/adult__the-house-in-the-cerulean-sea.jpg"),
    "The Last of Us": require("./images/adult__the-last-of-us.jpg"),
    "The Last of Us Part II": require("./images/adult__the-last-of-us-part-ii.jpg"),
    "The Leftovers": require("./images/adult__the-leftovers.jpg"),
    "The Legend of Zelda: Tears of the Kingdom": require("./images/adult__the-legend-of-zelda-tears-of-the-kingdom.jpg"),
    "The Magnus Archives": require("./images/adult__the-magnus-archives.jpg"),
    "The Martian": require("./images/adult__the-martian.jpg"),
    "The Matrix": require("./images/adult__the-matrix.jpg"),
    "The Moth": require("./images/adult__the-moth.jpg"),
    "The Name of the Wind": require("./images/adult__the-name-of-the-wind.jpg"),
    "The Night Circus": require("./images/adult__the-night-circus.jpg"),
    "The Notebook": require("./images/adult__the-notebook.jpg"),
    "The Poppy War": require("./images/adult__the-poppy-war.jpg"),
    "The Prestige": require("./images/adult__the-prestige.jpg"),
    "The Queen's Gambit": require("./images/adult__the-queens-gambit.jpg"),
    "The Road": require("./images/adult__the-road.jpg"),
    "The Seven Husbands of Evelyn Hugo": require("./images/adult__the-seven-husbands-of-evelyn-hugo.jpg"),
    "The Shadow of the Wind": require("./images/adult__the-shadow-of-the-wind.jpg"),
    "The Shape of Water": require("./images/adult__the-shape-of-water.jpg"),
    "The Shawshank Redemption": require("./images/adult__the-shawshank-redemption.jpg"),
    "The Silent Patient": require("./images/adult__the-silent-patient.jpg"),
    "The Sopranos": require("./images/adult__the-sopranos.jpg"),
    "The Witcher 3: Wild Hunt": require("./images/adult__the-witcher-3-wild-hunt.jpg"),
    "This American Life": require("./images/adult__this-american-life.jpg"),
    "True Detective": require("./images/adult__true-detective.jpg"),
    "Welcome to Night Vale": require("./images/adult__welcome-to-night-vale.jpg"),
    "Westworld": require("./images/adult__westworld.jpg"),
    "Wolf 359": require("./images/adult__wolf-359.jpg"),
    "You Must Remember This": require("./images/adult__you-must-remember-this.jpg"),
    "You're Wrong About": require("./images/adult__youre-wrong-about.jpg"),
  },
  "k2": {
    "A Short Hike": require("./images/k2__a-short-hike.jpg"),
    "Ada Twist, Scientist": require("./images/k2__ada-twist-scientist.jpg"),
    "Alba: A Wildlife Adventure": require("./images/k2__alba-a-wildlife-adventure.jpg"),
    "Alexander and the Terrible, Horrible, No Good, Very Bad Day": require("./images/k2__alexander-and-the-terrible-horrible-no-good-very-bad-day.jpg"),
    "Animal Crossing: New Horizons": require("./images/k2__animal-crossing-new-horizons.jpg"),
    "Blue’s Clues & You!": require("./images/k2__blues-clues-you.jpg"),
    "Bluey": require("./images/k2__bluey.jpg"),
    "Brown Bear, Brown Bear, What Do You See?": require("./images/k2__brown-bear-brown-bear-what-do-you-see.jpg"),
    "Caps for Sale": require("./images/k2__caps-for-sale.jpg"),
    "Cars": require("./images/k2__cars.jpg"),
    "Chicka Chicka Boom Boom": require("./images/k2__chicka-chicka-boom-boom.jpg"),
    "Click, Clack, Moo: Cows That Type": require("./images/k2__click-clack-moo-cows-that-type.jpg"),
    "Clifford the Big Red Dog": require("./images/k2__clifford-the-big-red-dog.jpg"),
    "Cloudy with a Chance of Meatballs": require("./images/k2__cloudy-with-a-chance-of-meatballs.jpg"),
    "Corduroy": require("./images/k2__corduroy.jpg"),
    "Creative Galaxy": require("./images/k2__creative-galaxy.jpg"),
    "Creepy Carrots!": require("./images/k2__creepy-carrots.jpg"),
    "Curious George": require("./images/k2__curious-george.jpg"),
    "Curious George (2006)": require("./images/k2__curious-george-2006.jpg"),
    "Daniel Tiger’s Neighborhood": require("./images/k2__daniel-tigers-neighborhood.jpg"),
    "Disney Dreamlight Valley": require("./images/k2__disney-dreamlight-valley.jpg"),
    "Don't Let the Pigeon Drive the Bus!": require("./images/k2__dont-let-the-pigeon-drive-the-bus.jpg"),
    "Don’t Let the Pigeon Drive the Bus!": require("./images/k2__dont-let-the-pigeon-drive-the-bus.jpg"),
    "Dragons Love Tacos": require("./images/k2__dragons-love-tacos.jpg"),
    "Elephant & Piggie: My New Friend Is So Fun!": require("./images/k2__elephant-piggie-my-new-friend-is-so-fun.jpg"),
    "Finding Nemo": require("./images/k2__finding-nemo.jpg"),
    "First Big Book of Animals": require("./images/k2__first-big-book-of-animals.jpg"),
    "Franklin": require("./images/k2__franklin.jpg"),
    "Frog and Toad Are Friends": require("./images/k2__frog-and-toad-are-friends.jpg"),
    "Froggy Gets Dressed": require("./images/k2__froggy-gets-dressed.jpg"),
    "Giraffes Can't Dance": require("./images/k2__giraffes-cant-dance.jpg"),
    "Go, Dog. Go!": require("./images/k2__go-dog-go.jpg"),
    "Goodnight Moon": require("./images/k2__goodnight-moon.jpg"),
    "Goodnight, Goodnight, Construction Site": require("./images/k2__goodnight-goodnight-construction-site.jpg"),
    "Green Eggs and Ham": require("./images/k2__green-eggs-and-ham.jpg"),
    "Harold and the Purple Crayon": require("./images/k2__harold-and-the-purple-crayon.jpg"),
    "How Do Dinosaurs Say Goodnight?": require("./images/k2__how-do-dinosaurs-say-goodnight.jpg"),
    "I Am a Frog!": require("./images/k2__i-am-a-frog.jpg"),
    "I Want My Hat Back": require("./images/k2__i-want-my-hat-back.jpg"),
    "If You Give a Mouse a Cookie": require("./images/k2__if-you-give-a-mouse-a-cookie.jpg"),
    "Inside Out": require("./images/k2__inside-out.jpg"),
    "Interrupting Chicken": require("./images/k2__interrupting-chicken.jpg"),
    "Kiki's Delivery Service": require("./images/k2__kikis-delivery-service.jpg"),
    "Kirby and the Forgotten Land": require("./images/k2__kirby-and-the-forgotten-land.jpg"),
    "Last Stop on Market Street": require("./images/k2__last-stop-on-market-street.jpg"),
    "LEGO City Undercover": require("./images/k2__lego-city-undercover.jpg"),
    "LEGO Marvel Super Heroes": require("./images/k2__lego-marvel-super-heroes.jpg"),
    "Lil Gator Game": require("./images/k2__lil-gator-game.jpg"),
    "Little Bear": require("./images/k2__little-bear.jpg"),
    "Llama Llama Red Pajama": require("./images/k2__llama-llama-red-pajama.jpg"),
    "Madeline": require("./images/k2__madeline.jpg"),
    "Mario Kart 8 Deluxe": require("./images/k2__mario-kart-8-deluxe.jpg"),
    "Minecraft": require("./images/k2__minecraft.jpg"),
    "Mister Rogers’ Neighborhood": require("./images/k2__mister-rogers-neighborhood.jpg"),
    "Molly of Denali": require("./images/k2__molly-of-denali.jpg"),
    "Monsters, Inc.": require("./images/k2__monsters-inc.jpg"),
    "My Little Pony: Friendship Is Magic": require("./images/k2__my-little-pony-friendship-is-magic.jpg"),
    "My Neighbor Totoro": require("./images/k2__my-neighbor-totoro.jpg"),
    "Nanette's Baguette": require("./images/k2__nanettes-baguette.jpg"),
    "New Pokémon Snap": require("./images/k2__new-pokemon-snap.jpg"),
    "No, David!": require("./images/k2__no-david.jpg"),
    "Not a Box": require("./images/k2__not-a-box.jpg"),
    "Numberblocks": require("./images/k2__numberblocks.jpg"),
    "Octonauts": require("./images/k2__octonauts.jpg"),
    "Olivia": require("./images/k2__olivia.jpg"),
    "Paddington": require("./images/k2__paddington.jpg"),
    "Paddington 2": require("./images/k2__paddington-2.jpg"),
    "Paw Patrol": require("./images/k2__paw-patrol.jpg"),
    "Paw Patrol: On a Roll!": require("./images/k2__paw-patrol-on-a-roll.jpg"),
    "Peg + Cat": require("./images/k2__peg-cat.jpg"),
    "Pete the Cat and the Missing Cupcakes": require("./images/k2__pete-the-cat-and-the-missing-cupcakes.jpg"),
    "Pete the Cat: I Love My White Shoes": require("./images/k2__pete-the-cat-i-love-my-white-shoes.jpg"),
    "Pokémon: Let’s Go, Pikachu! / Eevee!": require("./images/k2__pokemon-lets-go-pikachu-eevee.jpg"),
    "Puffin Rock": require("./images/k2__puffin-rock.jpg"),
    "Ratatouille": require("./images/k2__ratatouille.jpg"),
    "Room on the Broom": require("./images/k2__room-on-the-broom.jpg"),
    "Sarah & Duck": require("./images/k2__sarah-duck.jpg"),
    "Scribblenauts Unlimited": require("./images/k2__scribblenauts-unlimited.jpg"),
    "Sesame Street": require("./images/k2__sesame-street.jpg"),
    "StoryBots": require("./images/k2__storybots.jpg"),
    "Super Mario Odyssey": require("./images/k2__super-mario-odyssey.jpg"),
    "Super Why!": require("./images/k2__super-why.jpg"),
    "The Bad Seed": require("./images/k2__the-bad-seed.jpg"),
    "The Book with No Pictures": require("./images/k2__the-book-with-no-pictures.jpg"),
    "The Cat in the Hat": require("./images/k2__the-cat-in-the-hat.jpg"),
    "The Color Monster": require("./images/k2__the-color-monster.jpg"),
    "The Day the Crayons Quit": require("./images/k2__the-day-the-crayons-quit.jpg"),
    "The Gruffalo": require("./images/k2__the-gruffalo.jpg"),
    "The Incredibles": require("./images/k2__the-incredibles.jpg"),
    "The Invisible String": require("./images/k2__the-invisible-string.jpg"),
    "The Little Engine That Could": require("./images/k2__the-little-engine-that-could.jpg"),
    "The Many Adventures of Winnie the Pooh": require("./images/k2__the-many-adventures-of-winnie-the-pooh.jpg"),
    "The Mitten": require("./images/k2__the-mitten.jpg"),
    "The Monster at the End of This Book": require("./images/k2__the-monster-at-the-end-of-this-book.jpg"),
    "The Paper Bag Princess": require("./images/k2__the-paper-bag-princess.jpg"),
    "The Peanuts Movie": require("./images/k2__the-peanuts-movie.jpg"),
    "The Polar Express": require("./images/k2__the-polar-express.jpg"),
    "The Pout-Pout Fish": require("./images/k2__the-pout-pout-fish.jpg"),
    "The Rainbow Fish": require("./images/k2__the-rainbow-fish.jpg"),
    "The Secret Life of Pets": require("./images/k2__the-secret-life-of-pets.jpg"),
    "The Snowy Day": require("./images/k2__the-snowy-day.jpg"),
    "The Tale of Peter Rabbit": require("./images/k2__the-tale-of-peter-rabbit.jpg"),
    "The True Story of the 3 Little Pigs": require("./images/k2__the-true-story-of-the-3-little-pigs.jpg"),
    "The Very Hungry Caterpillar": require("./images/k2__the-very-hungry-caterpillar.jpg"),
    "There’s a Monster at the End of This Book": require("./images/k2__theres-a-monster-at-the-end-of-this-book.jpg"),
    "Toy Story": require("./images/k2__toy-story.jpg"),
    "Trash Truck": require("./images/k2__trash-truck.jpg"),
    "Tumble Leaf": require("./images/k2__tumble-leaf.jpg"),
    "Unicorn Academy": require("./images/k2__unicorn-academy.jpg"),
    "Untitled Goose Game": require("./images/k2__untitled-goose-game.jpg"),
    "WALL·E": require("./images/k2__walle.jpg"),
    "We Are in a Book!": require("./images/k2__we-are-in-a-book.jpg"),
    "We're Going on a Bear Hunt": require("./images/k2__were-going-on-a-bear-hunt.jpg"),
    "Where the Wild Things Are": require("./images/k2__where-the-wild-things-are.jpg"),
    "Wild Kratts": require("./images/k2__wild-kratts.jpg"),
    "Winnie the Pooh (2011)": require("./images/k2__winnie-the-pooh-2011.jpg"),
    "Yoshi’s Crafted World": require("./images/k2__yoshis-crafted-world.jpg"),
  },
  "36": {
    "5-Minute Crafts Kids": require("./images/36__5-minute-crafts-kids.jpg"),
    "Adventure Time": require("./images/36__adventure-time.jpg"),
    "Among the Hidden": require("./images/36__among-the-hidden.jpg"),
    "Animal Crossing": require("./images/36__animal-crossing.jpg"),
    "Avatar: The Last Airbender": require("./images/36__avatar-the-last-airbender.jpg"),
    "Beyblade": require("./images/36__beyblade.jpg"),
    "Big Hero 6": require("./images/36__big-hero-6.jpg"),
    "BrainPOP": require("./images/36__brainpop.jpg"),
    "Brawl Stars": require("./images/36__brawl-stars.jpg"),
    "Captain Underpants": require("./images/36__captain-underpants.jpg"),
    "Carmen Sandiego": require("./images/36__carmen-sandiego.jpg"),
    "Charlie and the Chocolate Factory": require("./images/36__charlie-and-the-chocolate-factory.jpg"),
    "Clash Royale": require("./images/36__clash-royale.jpg"),
    "Crash Course Kids": require("./images/36__crash-course-kids.jpg"),
    "DanTDM": require("./images/36__dantdm.jpg"),
    "Despicable Me": require("./images/36__despicable-me.jpg"),
    "Detective Pikachu": require("./images/36__detective-pikachu.jpg"),
    "Diary of a Wimpy Kid": require("./images/36__diary-of-a-wimpy-kid.jpg"),
    "Dog Man": require("./images/36__dog-man.jpg"),
    "Dream": require("./images/36__dream.jpg"),
    "DuckTales": require("./images/36__ducktales.jpg"),
    "Dude Perfect": require("./images/36__dude-perfect.jpg"),
    "Encanto": require("./images/36__encanto.jpg"),
    "Fall Guys": require("./images/36__fall-guys.jpg"),
    "Fortnite": require("./images/36__fortnite.jpg"),
    "Frindle": require("./images/36__frindle.jpg"),
    "Frozen": require("./images/36__frozen.jpg"),
    "Frozen II": require("./images/36__frozen-ii.jpg"),
    "Game Grumps": require("./images/36__game-grumps.jpg"),
    "Goosebumps": require("./images/36__goosebumps.jpg"),
    "Gravity Falls": require("./images/36__gravity-falls.jpg"),
    "Harry Potter and the Chamber of Secrets": require("./images/36__harry-potter-and-the-chamber-of-secrets.jpg"),
    "Harry Potter and the Sorcerer's Stone": require("./images/36__harry-potter-and-the-sorcerers-stone.jpg"),
    "Holes": require("./images/36__holes.jpg"),
    "How to Train Your Dragon": require("./images/36__how-to-train-your-dragon.jpg"),
    "How to Train Your Dragon 2": require("./images/36__how-to-train-your-dragon-2.jpg"),
    "Inkheart": require("./images/36__inkheart.jpg"),
    "Jurassic World Camp Cretaceous": require("./images/36__jurassic-world-camp-cretaceous.jpg"),
    "Just Dance": require("./images/36__just-dance.jpg"),
    "Kurzgesagt – In a Nutshell": require("./images/36__kurzgesagt-in-a-nutshell.jpg"),
    "LDShadowLady": require("./images/36__ldshadowlady.jpg"),
    "LEGO Games": require("./images/36__lego-games.jpg"),
    "LEGO Ninjago": require("./images/36__lego-ninjago.jpg"),
    "Luca": require("./images/36__luca.jpg"),
    "Mario Kart 8": require("./images/36__mario-kart-8.jpg"),
    "Mario Party": require("./images/36__mario-party.jpg"),
    "Mark Rober": require("./images/36__mark-rober.jpg"),
    "Matilda": require("./images/36__matilda.jpg"),
    "Minecraft": require("./images/36__minecraft.jpg"),
    "Minions": require("./images/36__minions.jpg"),
    "Miraculous: Tales of Ladybug & Cat Noir": require("./images/36__miraculous-tales-of-ladybug-cat-noir.jpg"),
    "Moana": require("./images/36__moana.jpg"),
    "MrBeast": require("./images/36__mrbeast.jpg"),
    "Nat Geo Kids": require("./images/36__nat-geo-kids.jpg"),
    "Ninja": require("./images/36__ninja.jpg"),
    "Paddington": require("./images/36__paddington.jpg"),
    "Pokémon": require("./images/36__pokemon.jpg"),
    "Pokémon Games": require("./images/36__pokemon-games.jpg"),
    "Pokimane": require("./images/36__pokimane.jpg"),
    "PrestonPlayz": require("./images/36__prestonplayz.jpg"),
    "Redwall": require("./images/36__redwall.jpg"),
    "Roblox": require("./images/36__roblox.jpg"),
    "Rocket League": require("./images/36__rocket-league.jpg"),
    "Ryan's World": require("./images/36__ryans-world.jpg"),
    "Sideways Stories from Wayside School": require("./images/36__sideways-stories-from-wayside-school.jpg"),
    "Sing": require("./images/36__sing.jpg"),
    "Sing 2": require("./images/36__sing-2.jpg"),
    "Sonic Games": require("./images/36__sonic-games.jpg"),
    "Sonic the Hedgehog": require("./images/36__sonic-the-hedgehog.jpg"),
    "Sonic the Hedgehog 2": require("./images/36__sonic-the-hedgehog-2.jpg"),
    "Spider-Man: Into the Spider-Verse": require("./images/36__spider-man-into-the-spider-verse.jpg"),
    "Splatoon": require("./images/36__splatoon.jpg"),
    "SpongeBob SquarePants": require("./images/36__spongebob-squarepants.jpg"),
    "SSundee": require("./images/36__ssundee.jpg"),
    "Star Wars Rebels": require("./images/36__star-wars-rebels.jpg"),
    "Star Wars: The Clone Wars": require("./images/36__star-wars-the-clone-wars.jpg"),
    "Steven Universe": require("./images/36__steven-universe.jpg"),
    "Subway Surfers": require("./images/36__subway-surfers.jpg"),
    "Super Mario Odyssey": require("./images/36__super-mario-odyssey.jpg"),
    "Super Smash Bros.": require("./images/36__super-smash-bros.jpg"),
    "TED-Ed": require("./images/36__ted-ed.jpg"),
    "Teen Titans Go!": require("./images/36__teen-titans-go.jpg"),
    "Tetris": require("./images/36__tetris.jpg"),
    "The 39 Clues": require("./images/36__the-39-clues.jpg"),
    "The Amazing World of Gumball": require("./images/36__the-amazing-world-of-gumball.jpg"),
    "The BFG": require("./images/36__the-bfg.jpg"),
    "The Dragon Prince": require("./images/36__the-dragon-prince.jpg"),
    "The Legend of Korra": require("./images/36__the-legend-of-korra.jpg"),
    "The Legend of Zelda: Breath of the Wild": require("./images/36__the-legend-of-zelda-breath-of-the-wild.jpg"),
    "The Lightning Thief": require("./images/36__the-lightning-thief.jpg"),
    "The Lion, the Witch and the Wardrobe": require("./images/36__the-lion-the-witch-and-the-wardrobe.jpg"),
    "The Loud House": require("./images/36__the-loud-house.jpg"),
    "The Mitchells vs. the Machines": require("./images/36__the-mitchells-vs-the-machines.jpg"),
    "The Sea of Monsters": require("./images/36__the-sea-of-monsters.jpg"),
    "ThinkNoodles": require("./images/36__thinknoodles.jpg"),
    "Toy Story": require("./images/36__toy-story.jpg"),
    "Toy Story 4": require("./images/36__toy-story-4.jpg"),
    "Unspeakable": require("./images/36__unspeakable.jpg"),
    "Voltron: Legendary Defender": require("./images/36__voltron-legendary-defender.jpg"),
    "Wonder": require("./images/36__wonder.jpg"),
  },
  "ms_hs": {
    "86": require("./images/mshs__86.jpg"),
    "A Good Girl's Guide to Murder": require("./images/mshs__a-good-girls-guide-to-murder.jpg"),
    "A Monster Calls": require("./images/mshs__a-monster-calls.jpg"),
    "A Quiet Place": require("./images/mshs__a-quiet-place.jpg"),
    "A Series of Unfortunate Events": require("./images/mshs__a-series-of-unfortunate-events.jpg"),
    "A Silent Voice": require("./images/mshs__a-silent-voice.jpg"),
    "Ace Attorney": require("./images/mshs__ace-attorney.jpg"),
    "Akeelah and the Bee": require("./images/mshs__akeelah-and-the-bee.jpg"),
    "Among Us": require("./images/mshs__among-us.jpg"),
    "An Ember in the Ashes": require("./images/mshs__an-ember-in-the-ashes.jpg"),
    "Animal Crossing: New Horizons": require("./images/mshs__animal-crossing-new-horizons.jpg"),
    "Anne with an E": require("./images/mshs__anne-with-an-e.jpg"),
    "Arcane": require("./images/mshs__arcane.jpg"),
    "Aristotle and Dante Discover the Secrets of the Universe": require("./images/mshs__aristotle-and-dante-discover-the-secrets-of-the-universe.jpg"),
    "Arrival": require("./images/mshs__arrival.jpg"),
    "Assassination Classroom": require("./images/mshs__assassination-classroom.jpg"),
    "Attack on Titan": require("./images/mshs__attack-on-titan.jpg"),
    "Avatar: The Last Airbender": require("./images/mshs__avatar-the-last-airbender.jpg"),
    "Black Clover": require("./images/mshs__black-clover.jpg"),
    "Bleach": require("./images/mshs__bleach.jpg"),
    "Blue Lock": require("./images/mshs__blue-lock.jpg"),
    "Bridgerton": require("./images/mshs__bridgerton.jpg"),
    "Buffy the Vampire Slayer": require("./images/mshs__buffy-the-vampire-slayer.jpg"),
    "Bungo Stray Dogs": require("./images/mshs__bungo-stray-dogs.jpg"),
    "Caraval": require("./images/mshs__caraval.jpg"),
    "Catching Fire": require("./images/mshs__catching-fire.jpg"),
    "Celeste": require("./images/mshs__celeste.jpg"),
    "Cemetery Boys": require("./images/mshs__cemetery-boys.jpg"),
    "Chainsaw Man": require("./images/mshs__chainsaw-man.jpg"),
    "Chaos Walking: The Knife of Never Letting Go": require("./images/mshs__chaos-walking-the-knife-of-never-letting-go.jpg"),
    "Children of Blood and Bone": require("./images/mshs__children-of-blood-and-bone.jpg"),
    "Cobra Kai": require("./images/mshs__cobra-kai.jpg"),
    "Code Geass": require("./images/mshs__code-geass.jpg"),
    "Code Name Verity": require("./images/mshs__code-name-verity.jpg"),
    "Control": require("./images/mshs__control.jpg"),
    "Cowboy Bebop": require("./images/mshs__cowboy-bebop.jpg"),
    "Crooked Kingdom": require("./images/mshs__crooked-kingdom.jpg"),
    "Cruella": require("./images/mshs__cruella.jpg"),
    "Cyberpunk 2077": require("./images/mshs__cyberpunk-2077.jpg"),
    "Dead Poets Society": require("./images/mshs__dead-poets-society.jpg"),
    "Dear Martin": require("./images/mshs__dear-martin.jpg"),
    "Death Note": require("./images/mshs__death-note.jpg"),
    "Demon Slayer: Kimetsu no Yaiba": require("./images/mshs__demon-slayer-kimetsu-no-yaiba.jpg"),
    "Disco Elysium": require("./images/mshs__disco-elysium.jpg"),
    "Divergent": require("./images/mshs__divergent.jpg"),
    "Doctor Who": require("./images/mshs__doctor-who.jpg"),
    "Dr. Stone": require("./images/mshs__dr-stone.jpg"),
    "Dungeons & Dragons: Honor Among Thieves": require("./images/mshs__dungeons-dragons-honor-among-thieves.jpg"),
    "Edge of Tomorrow": require("./images/mshs__edge-of-tomorrow.jpg"),
    "Eleanor & Park": require("./images/mshs__eleanor-park.jpg"),
    "Enola Holmes": require("./images/mshs__enola-holmes.jpg"),
    "Eragon": require("./images/mshs__eragon.jpg"),
    "Erased": require("./images/mshs__erased.jpg"),
    "Everything Everywhere All at Once": require("./images/mshs__everything-everywhere-all-at-once.jpg"),
    "Fangirl": require("./images/mshs__fangirl.jpg"),
    "Firewatch": require("./images/mshs__firewatch.jpg"),
    "Fortnite": require("./images/mshs__fortnite.jpg"),
    "Friday Night Lights": require("./images/mshs__friday-night-lights.jpg"),
    "Frieren: Beyond Journey's End": require("./images/mshs__frieren-beyond-journeys-end.jpg"),
    "Fullmetal Alchemist: Brotherhood": require("./images/mshs__fullmetal-alchemist-brotherhood.jpg"),
    "Get Out": require("./images/mshs__get-out.jpg"),
    "Gladiator": require("./images/mshs__gladiator.jpg"),
    "Hades": require("./images/mshs__hades.jpg"),
    "Haikyu!!": require("./images/mshs__haikyu.jpg"),
    "Harry Potter and the Prisoner of Azkaban": require("./images/mshs__harry-potter-and-the-prisoner-of-azkaban.jpg"),
    "Harry Potter and the Sorcerer's Stone": require("./images/mshs__harry-potter-and-the-sorcerers-stone.jpg"),
    "Heartstopper": require("./images/mshs__heartstopper.jpg"),
    "Heartstopper: Volume 1": require("./images/mshs__heartstopper-volume-1.jpg"),
    "Hi-Fi Rush": require("./images/mshs__hi-fi-rush.jpg"),
    "His Dark Materials": require("./images/mshs__his-dark-materials.jpg"),
    "His Dark Materials: The Golden Compass": require("./images/mshs__his-dark-materials-the-golden-compass.jpg"),
    "Hollow Knight": require("./images/mshs__hollow-knight.jpg"),
    "Horimiya": require("./images/mshs__horimiya.jpg"),
    "How to Train Your Dragon": require("./images/mshs__how-to-train-your-dragon.jpg"),
    "Hunter × Hunter": require("./images/mshs__hunter-hunter.jpg"),
    "Inception": require("./images/mshs__inception.jpg"),
    "Jujutsu Kaisen": require("./images/mshs__jujutsu-kaisen.jpg"),
    "Jurassic Park": require("./images/mshs__jurassic-park.jpg"),
    "Knives Out": require("./images/mshs__knives-out.jpg"),
    "Kuroko's Basketball": require("./images/mshs__kurokos-basketball.jpg"),
    "Lady Bird": require("./images/mshs__lady-bird.jpg"),
    "Legend": require("./images/mshs__legend.jpg"),
    "Legendborn": require("./images/mshs__legendborn.jpg"),
    "Life Is Strange": require("./images/mshs__life-is-strange.jpg"),
    "Little Women": require("./images/mshs__little-women.jpg"),
    "Lockwood & Co.": require("./images/mshs__lockwood-co.jpg"),
    "Long Way Down": require("./images/mshs__long-way-down.jpg"),
    "Looking for Alaska": require("./images/mshs__looking-for-alaska.jpg"),
    "Lore Olympus: Volume One": require("./images/mshs__lore-olympus-volume-one.jpg"),
    "Love, Simon": require("./images/mshs__love-simon.jpg"),
    "Marvel's Guardians of the Galaxy": require("./images/mshs__marvels-guardians-of-the-galaxy.jpg"),
    "Mass Effect": require("./images/mshs__mass-effect.jpg"),
    "Merlin": require("./images/mshs__merlin.jpg"),
    "Minecraft": require("./images/mshs__minecraft.jpg"),
    "Miss Peregrine's Home for Peculiar Children": require("./images/mshs__miss-peregrines-home-for-peculiar-children.jpg"),
    "Mob Psycho 100": require("./images/mshs__mob-psycho-100.jpg"),
    "Moriarty the Patriot": require("./images/mshs__moriarty-the-patriot.jpg"),
    "My Hero Academia": require("./images/mshs__my-hero-academia.jpg"),
    "Naruto": require("./images/mshs__naruto.jpg"),
    "Natsume's Book of Friends": require("./images/mshs__natsumes-book-of-friends.jpg"),
    "Neon Genesis Evangelion": require("./images/mshs__neon-genesis-evangelion.jpg"),
    "Never Have I Ever": require("./images/mshs__never-have-i-ever.jpg"),
    "Night in the Woods": require("./images/mshs__night-in-the-woods.jpg"),
    "Nimona": require("./images/mshs__nimona.jpg"),
    "Noragami": require("./images/mshs__noragami.jpg"),
    "Now You See Me": require("./images/mshs__now-you-see-me.jpg"),
    "One of Us Is Lying": require("./images/mshs__one-of-us-is-lying.jpg"),
    "One Piece": require("./images/mshs__one-piece.jpg"),
    "Outer Banks": require("./images/mshs__outer-banks.jpg"),
    "Overwatch 2": require("./images/mshs__overwatch-2.jpg"),
    "Oxenfree": require("./images/mshs__oxenfree.jpg"),
    "Peaky Blinders": require("./images/mshs__peaky-blinders.jpg"),
    "Percy Jackson & the Olympians: The Lightning Thief": require("./images/mshs__percy-jackson-the-olympians-the-lightning-thief.jpg"),
    "Percy Jackson and the Olympians": require("./images/mshs__percy-jackson-and-the-olympians.jpg"),
    "Persona 5 Royal": require("./images/mshs__persona-5-royal.jpg"),
    "Portal 2": require("./images/mshs__portal-2.jpg"),
    "Psycho-Pass": require("./images/mshs__psycho-pass.jpg"),
    "Ready Player One": require("./images/mshs__ready-player-one.jpg"),
    "Red Dead Redemption 2": require("./images/mshs__red-dead-redemption-2.jpg"),
    "Rocket League": require("./images/mshs__rocket-league.jpg"),
    "Rocky": require("./images/mshs__rocky.jpg"),
    "School Spirits": require("./images/mshs__school-spirits.jpg"),
    "Scott Pilgrim vs. the World": require("./images/mshs__scott-pilgrim-vs-the-world.jpg"),
    "Scythe": require("./images/mshs__scythe.jpg"),
    "Sea of Stars": require("./images/mshs__sea-of-stars.jpg"),
    "Shadow and Bone": require("./images/mshs__shadow-and-bone.jpg"),
    "Sherlock": require("./images/mshs__sherlock.jpg"),
    "Simon vs. the Homo Sapiens Agenda": require("./images/mshs__simon-vs-the-homo-sapiens-agenda.jpg"),
    "Six of Crows": require("./images/mshs__six-of-crows.jpg"),
    "Sk8 the Infinity": require("./images/mshs__sk8-the-infinity.jpg"),
    "Slay the Spire": require("./images/mshs__slay-the-spire.jpg"),
    "Smallville": require("./images/mshs__smallville.jpg"),
    "Speak": require("./images/mshs__speak.jpg"),
    "Spider-Man: Homecoming": require("./images/mshs__spider-man-homecoming.jpg"),
    "Spider-Man: Into the Spider-Verse": require("./images/mshs__spider-man-into-the-spider-verse.jpg"),
    "Spiritfarer": require("./images/mshs__spiritfarer.jpg"),
    "Splatoon 3": require("./images/mshs__splatoon-3.jpg"),
    "Spy × Family": require("./images/mshs__spy-family.jpg"),
    "Stardew Valley": require("./images/mshs__stardew-valley.jpg"),
    "Steins;Gate": require("./images/mshs__steinsgate.jpg"),
    "Stranger Things": require("./images/mshs__stranger-things.jpg"),
    "Subnautica": require("./images/mshs__subnautica.jpg"),
    "Supernatural": require("./images/mshs__supernatural.jpg"),
    "Sweet Tooth": require("./images/mshs__sweet-tooth.jpg"),
    "Sword Art Online": require("./images/mshs__sword-art-online.jpg"),
    "Ted Lasso": require("./images/mshs__ted-lasso.jpg"),
    "The 100": require("./images/mshs__the-100.jpg"),
    "The Batman": require("./images/mshs__the-batman.jpg"),
    "The Book of Dust": require("./images/mshs__the-book-of-dust.jpg"),
    "The Book Thief": require("./images/mshs__the-book-thief.jpg"),
    "The Conjuring": require("./images/mshs__the-conjuring.jpg"),
    "The Cruel Prince": require("./images/mshs__the-cruel-prince.jpg"),
    "The Dark Knight": require("./images/mshs__the-dark-knight.jpg"),
    "The Dragon Prince": require("./images/mshs__the-dragon-prince.jpg"),
    "The Edge of Seventeen": require("./images/mshs__the-edge-of-seventeen.jpg"),
    "The Elder Scrolls V: Skyrim": require("./images/mshs__the-elder-scrolls-v-skyrim.jpg"),
    "The Fault in Our Stars": require("./images/mshs__the-fault-in-our-stars.jpg"),
    "The Giver": require("./images/mshs__the-giver.jpg"),
    "The Good Place": require("./images/mshs__the-good-place.jpg"),
    "The Half of It": require("./images/mshs__the-half-of-it.jpg"),
    "The Hate U Give": require("./images/mshs__the-hate-u-give.jpg"),
    "The Hunger Games": require("./images/mshs__the-hunger-games.jpg"),
    "The Karate Kid": require("./images/mshs__the-karate-kid.jpg"),
    "The Last of Us": require("./images/mshs__the-last-of-us.jpg"),
    "The Legend of Korra": require("./images/mshs__the-legend-of-korra.jpg"),
    "The Legend of Zelda: Breath of the Wild": require("./images/mshs__the-legend-of-zelda-breath-of-the-wild.jpg"),
    "The Legend of Zelda: Tears of the Kingdom": require("./images/mshs__the-legend-of-zelda-tears-of-the-kingdom.jpg"),
    "The Lord of the Rings: The Fellowship of the Ring": require("./images/mshs__the-lord-of-the-rings-the-fellowship-of-the-ring.jpg"),
    "The Mandalorian": require("./images/mshs__the-mandalorian.jpg"),
    "The Martian": require("./images/mshs__the-martian.jpg"),
    "The Maze Runner": require("./images/mshs__the-maze-runner.jpg"),
    "The Midnight Club": require("./images/mshs__the-midnight-club.jpg"),
    "The Outsiders": require("./images/mshs__the-outsiders.jpg"),
    "The Owl House": require("./images/mshs__the-owl-house.jpg"),
    "The Perks of Being a Wallflower": require("./images/mshs__the-perks-of-being-a-wallflower.jpg"),
    "The Princess Bride": require("./images/mshs__the-princess-bride.jpg"),
    "The Promised Neverland": require("./images/mshs__the-promised-neverland.jpg"),
    "The Queen's Gambit": require("./images/mshs__the-queens-gambit.jpg"),
    "The Sandman": require("./images/mshs__the-sandman.jpg"),
    "The Sea of Monsters": require("./images/mshs__the-sea-of-monsters.jpg"),
    "The Society": require("./images/mshs__the-society.jpg"),
    "The Summer I Turned Pretty": require("./images/mshs__the-summer-i-turned-pretty.jpg"),
    "The Truman Show": require("./images/mshs__the-truman-show.jpg"),
    "The Umbrella Academy": require("./images/mshs__the-umbrella-academy.jpg"),
    "The Walking Dead": require("./images/mshs__the-walking-dead.jpg"),
    "The Witcher": require("./images/mshs__the-witcher.jpg"),
    "The Witcher 3: Wild Hunt": require("./images/mshs__the-witcher-3-wild-hunt.jpg"),
    "They Both Die at the End": require("./images/mshs__they-both-die-at-the-end.jpg"),
    "To All the Boys I've Loved Before": require("./images/mshs__to-all-the-boys-ive-loved-before.jpg"),
    "Tokyo Ghoul": require("./images/mshs__tokyo-ghoul.jpg"),
    "Truly Devious": require("./images/mshs__truly-devious.jpg"),
    "Undertale": require("./images/mshs__undertale.jpg"),
    "Unpacking": require("./images/mshs__unpacking.jpg"),
    "Unwind": require("./images/mshs__unwind.jpg"),
    "Veronica Mars": require("./images/mshs__veronica-mars.jpg"),
    "Vinland Saga": require("./images/mshs__vinland-saga.jpg"),
    "Wednesday": require("./images/mshs__wednesday.jpg"),
    "Young Royals": require("./images/mshs__young-royals.jpg"),
    "Your Lie in April": require("./images/mshs__your-lie-in-april.jpg"),
    "Your Name": require("./images/mshs__your-name.jpg"),
  },
} as const;

export function getSwipeCardFallbackImage(deckKey: string, title: string) {
  return (swipeCardFallbackImages as any)?.[deckKey]?.[title] ?? null;
}
