/**
 * /about — Brief description of NovelIdeas and its purpose.
 */

import { ScrollView, StyleSheet, Text, View, SafeAreaView } from "react-native";
import BackToNovelIdeasHeader from "../components/BackToNovelIdeasHeader";
import { returnToNovelIdeas } from "../lib/secondaryRouteNavigation";

export default function AboutScreen() {
  return (
    <SafeAreaView style={styles.safe}>
      <BackToNovelIdeasHeader
        title="About"
        onPress={() => {
          void returnToNovelIdeas();
        }}
      />
      <ScrollView style={styles.body} contentContainerStyle={styles.bodyContent}>

        <View style={styles.logoRow}>
          <Text style={styles.logoText}>Novel</Text>
          <View style={styles.logoDivider} />
          <Text style={styles.logoText}>Ideas</Text>
        </View>
        <Text style={styles.tagline}>Book Finder</Text>

        <Text style={styles.description}>
          NovelIdeas is a reader-first book discovery app designed for libraries. It helps
          readers of all ages find their next great book through a fast, swipe-based preference
          interface — no account, no algorithm scores exposed, just the books.
        </Text>

        <Text style={styles.description}>
          Recommendations are generated by combining signals from multiple public book databases
          including Google Books, Open Library, Kitsu, and ComicVine. The recommendation engine
          is tuned continuously using anonymous human review data collected through the optional
          evaluation flow.
        </Text>

        <Text style={styles.description}>
          NovelIdeas is built to be safe for all ages, private by design, and simple enough to
          hand to a reader without explanation.
        </Text>

        <View style={styles.divider} />

        <Text style={styles.sectionHeading}>Version</Text>
        <Text style={styles.meta}>NovelIdeas 2.0</Text>

        <Text style={styles.sectionHeading}>Contact</Text>
        <Text style={styles.meta}>feedback@novelideas.app</Text>

      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: "#071526" },
  body: { flex: 1 },
  bodyContent: { padding: 20, paddingBottom: 40 },
  logoRow: { flexDirection: "row", alignItems: "center", marginBottom: 4 },
  logoText: { color: "#e5efff", fontSize: 28, fontWeight: "900" },
  logoDivider: { width: 2, height: 28, backgroundColor: "#f0c040", marginHorizontal: 8, borderRadius: 1 },
  tagline: { color: "#7ab3e0", fontSize: 13, fontWeight: "600", marginBottom: 24, letterSpacing: 0.5 },
  description: { color: "#b0c4de", fontSize: 15, lineHeight: 23, marginBottom: 16 },
  divider: { borderTopWidth: 1, borderTopColor: "#1e3a5f", marginVertical: 20 },
  sectionHeading: { color: "#c9d8f0", fontSize: 13, fontWeight: "800", textTransform: "uppercase", letterSpacing: 0.8, marginBottom: 4 },
  meta: { color: "#8aa8cc", fontSize: 14, marginBottom: 16 },
});
